### ISSUE TITLE
As a user, I would like to see a consistent display of metadata labels in all tools where there is a drop-down metadata field list

### ISSUE THREAD

**Issue by jblom** [beeldengeluid/labo-components#140]
@lilimelgar commented on [Wed Jul 18 2018](https://github.com/CLARIAH/wp5_mediasuite/issues/486)

This issue mostly applies to B&G metadata, but it should be consistent for the other collections as well. The Inspector tool shows in the production version (tested in Summer school) the ideal "order" for B&G metadata labels:

![screen shot 2018-07-18 at 13 42 14](https://user-images.githubusercontent.com/8133228/42879301-68c7ad40-8a90-11e8-8eba-b28cf39e9416.png)

But the Search tool (when creating a new facet) displays the old order:

![screen shot 2018-07-18 at 13 43 04](https://user-images.githubusercontent.com/8133228/42879329-86986d46-8a90-11e8-918b-ef927bcc7ae0.png)

**Comment by lilimelgar** [comment]
Solved
