### ISSUE TITLE
As a user, I would like to see the OCR data in the resource viewer

### ISSUE THREAD

**Issue by jblom** [beeldengeluid/labo-components#141]
@lilimelgar commented on [Wed Oct 10 2018](https://github.com/CLARIAH/wp5_mediasuite/issues/518)

This issue is divided in 2:

- [ ] Mainly for the Desmet paper collection, which includes OCR enrichments that can be used during search, it is important to show the OCR data, i.e., expose the content of the field "layer__ocr.text", plus the other fields that contain enrichments (see dictionary in the inspector). User request: "when retrieving an OCRed document from the paper collection the search term used is not highlighted in the metadata (nor the document) and can also not be found by using cmd f (both in metadata and doc). It would be very nice to be able to do that." Assign this part to https://github.com/hugolio (add as collaborator)

- [ ] Highlight search terms also in the resource viewer. This issue is also added in #93 for the search result list.

**Comment by lilimelgar** [comment]
Issue moved to [beeldengeluid/labs-importer #14](https://github.com/beeldengeluid/labs-importer/issues/14) via [**ZenHub**](https://www.zenhub.com/)
