### ISSUE TITLE
As a developer, I need to position the annotation tool/window in a way that doesn't cover the resource

### ISSUE THREAD

**Issue by jblom** [beeldengeluid/labo-components#143]
@lilimelgar commented on [Wed Oct 10 2018](https://github.com/CLARIAH/wp5_mediasuite/issues/517)

In v3, Desmet paper collection mostly, the annotation window/pop-up covers the image, making it difficult for the user to read while annotating:

![screen shot 2018-10-10 at 15 01 11](https://user-images.githubusercontent.com/8133228/46738070-80584380-cc9d-11e8-8ac5-578a216887bb.png)

This issue is for https://github.com/hugolio (add as collaborator).

**Comment by avlisodraude** [comment]
**@jblom @lilimelgar**
 
Issue for labo-components project done in branch:
_issue/#143-UI-enhancement_

### Pull request
https://github.com/beeldengeluid/labo-components/pull/412

### Screencast
https://drive.google.com/open?id=1krkReN7oPhvuVgh9ZEfXZRQ5ayo1wyEP

###  What's been done?
The annotations modal can now be dragged (this applies to every modal/FlexModal) and the background for the annotations modal in the item details recipe does not block the view so the user can see the resource he/she wants to annotate.

**Comment by jwassenaarbg** [comment]
@avlisodraude "the background for the annotations modal in the item details recipe does not block the view so the user can see the resource he/she wants to annotate." -> Does this mean that the modal is transparent? In my testing the background of the modal was not transparent (Tested using Oral History Reis van de Razzia collection).

The draggable modal works nice! Also like that you are able to retrieve the window when you accidentally drag it outside the view.

Changes are compact and understandable - looks good to me.

**Comment by jblom** [comment]
@avlisodraude @jwassenaarbg also tested this one and found one big flaw caused by the Draggable component: the impossibility to type anything in text fields. Fortunately this problem was fixed adding the property 

enableUserSelectHack={false}

I'm closing this issue now

**Comment by jblom** [comment]
@lilimelgar you can test this one as wel on test
