### ISSUE TITLE
As a developer, I need to use the same terms for referring to "bookmark group"

### ISSUE THREAD

**Issue by jblom** [beeldengeluid/labo-components#147]
@lilimelgar commented on [Wed Oct 10 2018](https://github.com/CLARIAH/wp5_mediasuite/issues/512)

Use Bookmark group instead of category in the bookmark window:

<img width="897" alt="screenshot 2018-07-03 15 05 22" src="https://user-images.githubusercontent.com/8133228/46734385-5437c500-cc93-11e8-97f9-655136b22387.png">

**Comment by lilimelgar** [comment]
Done in #180
