### ISSUE TITLE
As a developer, I need to implement improvements to the Inspector tool based on user input

### ISSUE THREAD

**Issue by jblom** [beeldengeluid/labo-components#148]
@lilimelgar commented on [Mon May 28 2018](https://github.com/CLARIAH/wp5_mediasuite/issues/426)

Redesigning the Inspector tool:

==Werner==
- [ ] Update field selection selects, to a list with: name, type, global completeness percentage*, short definition description in hover
(* requires the completeness query to respond fast; storing the results in the session storage for efficiency)
- [x] For each field add a popup with additional information about the field completeness
- [x] Remove the current pie charts with (relative) completeness
- [x] Support a default date field per collection
- [x] Store selected fields between collection switches

==Previous: meeting with Mari/Kaspar/Jaap==
- [x] Generate a new query for completeness of a single field (Mari)
- [x] Add option to visualize general completeness of a single field (not over time)
- [x] Add label for option to visualize over time
- [x] Flip around the fields for X and Y axes to view over time
- [x] Add behavior that nothing happens until user selects date field (for visualizing over time)
- [ ] Add collapsable menus for the different blocks/components, as in this one:
![screen shot 2018-07-16 at 14 34 59](https://user-images.githubusercontent.com/8133228/42758928-788fc078-8905-11e8-99de-92f44fbddf53.png)
- [x] Add tooltips in selection menus (at the end of V3 implementation, together with Epic #77)
- [x] Improve presentation of stats summary

---

@jblom commented on [Thu Aug 30 2018](https://github.com/CLARIAH/wp5_mediasuite/issues/426#issuecomment-417334232)

@lilimelgar is this done?

---

@lilimelgar commented on [Thu Aug 30 2018](https://github.com/CLARIAH/wp5_mediasuite/issues/426#issuecomment-417336757)

@jblom Most of the sub-issues are done, there is only one that I am not sure about:
(* requires the completeness query to respond fast; storing the results in the session storage for efficiency).

And this one would be nice but not a must: 
Add collapsable menus for the different blocks/components, as in this one:
![screen shot 2018-07-16 at 14 34 59](https://user-images.githubusercontent.com/8133228/42758928-788fc078-8905-11e8-99de-92f44fbddf53.png)

---

@jblom commented on [Thu Aug 30 2018](https://github.com/CLARIAH/wp5_mediasuite/issues/426#issuecomment-417338854)

@lilimelgar ok we'll check this out. Keeping it in the backlog

**Comment by lilimelgar** [comment]
Pending ToDos in this issue opened as new issues.
