### ISSUE TITLE
As a user, I need that the numbers are shown with decimal separators

### ISSUE THREAD

**Issue by jblom** [beeldengeluid/labo-components#150]
@lilimelgar commented on [Wed Oct 10 2018](https://github.com/CLARIAH/wp5_mediasuite/issues/511)

Add spaces as separators for numbers (groups of three), as recommended by international organizations ([here](https://en.wikipedia.org/wiki/Decimal_separator)). This applies to hit counts everywhere in the MS, to make it easier for users to understand if the collection has millions or thousands items. E.g., "1883516" items should be shown as: 1 883 516

**Comment by avlisodraude** [comment]
@lilimelgar @jblom 

### Issue done in branch (labo-components): ###
task/#150-format-numbers

### What was done? ###
A formating method according to the issue requirement was made in ComponentUtil
Format applied to number in Single Search tool and Collection Inspector

### Examples of changes: ###

#### For single search tool #### 
![Screenshot 2018-12-05 at 10.54.55.png](https://images.zenhubusercontent.com/5a1e745d8a75884b90892ac4/a1a3e453-19f9-4c2d-8573-792c369c22dd)

![Screenshot 2018-12-05 at 10.55.02.png](https://images.zenhubusercontent.com/5a1e745d8a75884b90892ac4/1da09ad0-d5fc-4e8a-8237-72e4f75695db)

![Screenshot 2018-12-05 at 10.55.09.png](https://images.zenhubusercontent.com/5a1e745d8a75884b90892ac4/71f8991b-6a40-497a-bc7e-a303b80102a9)


#### For Collection Inspector tool #### 
_Along with the number formatting some layout formatting was applied to the table (align results right)_
![Screenshot 2018-12-05 at 10.55.23.png](https://images.zenhubusercontent.com/5a1e745d8a75884b90892ac4/745f11fe-debd-4373-bd02-4af6cbba0e06)

**Comment by lilimelgar** [comment]
Checked in branch task/#150-format-numbers. All good! :)
@mwigham: please check if it is possible to format the numbers in the notebooks in the same way as done in this issue.

**Comment by mwigham** [comment]
Yes, this is possible.  New issue, or shall I just do it when I get back next week?

**Comment by jblom** [comment]
@mwigham @lilimelgar please put this in a new issue. I like closing things :-)

**Comment by jblom** [comment]
@avlisodraude @lilimelgar now this is also merged into master (so it looks good indeeddddd)
