### ISSUE TITLE
As a user, I expect to find a media object when the access icon indicates that the item can be viewed or played

### ISSUE THREAD

**Issue by jblom** [beeldengeluid/labo-components#151]
@lilimelgar commented on [Mon Feb 05 2018](https://github.com/CLARIAH/wp5_mediasuite/issues/302)

In the B&G Audiovisual collection, there are some results in the result list that show icons with the media type = image + icon showing that there is access option (e.g., 4937317@program, or:
![screen shot 2018-02-05 at 11 40 44](https://user-images.githubusercontent.com/8133228/35800537-8a27244a-0a69-11e8-932d-47d2cb2cd2fd.png)). However, the foto/image collection of B&G is not yet made available and these images cannot be viewed. We could add on "mouse over" in those cases: item can be viewed but it's not available in the MS yet, or something like that.

---

@avlisodraude commented on [Wed Jul 18 2018](https://github.com/CLARIAH/wp5_mediasuite/issues/302#issuecomment-405956304)

@lilimelgar : test if this still an issue.

**Comment by lilimelgar** [comment]
This is solved
