### ISSUE TITLE
As a user, I would like to copy the search parameters of my saved query

### ISSUE THREAD

**Issue by jblom** [beeldengeluid/labo-components#157]
@lilimelgar commented on [Mon Sep 24 2018](https://github.com/CLARIAH/wp5_mediasuite/issues/509)

Issue #440 was about showing the parameters of a saved query. This shows in a pop-up on mouse over. This issue is about facilitating the exporting/copying of those parameters as text, so the user can paste them in their reports/papers.

So, add a button either in the pop-up for copying, or an extra button in the query menu (now it has Delete and Open) for the same purpose.

![Screen Shot 2018-09-24 at 17.07.29.png](https://images.zenhubusercontent.com/5a115fba8a75884b9087ff7a/4e788310-5704-437a-b0e7-eb78110a6603)

**Comment by avlisodraude** [comment]
@lilimelgar @jblom 
Issue done in labo-components branch _"task/#157-copy-query-params-to-clipboard"_

**What has been done?** 

The query icon ![Screenshot 2018-12-17 at 09.05.55.png](https://images.zenhubusercontent.com/5a1e745d8a75884b90892ac4/bb2409fb-add1-49cb-8533-bec3e7964570) has been changed into a button so now alongside with showing the current query on hover once the button is clicked the query itself is saved to the clipboard as shown in the following screencast 
https://drive.google.com/open?id=1bqgZADoBySHENLDTESAd8oe7FRNd1NVR

The functionality has been tested in Chrome, Safari and Firefox latest version (No IE testing done). In all those cases it worked as expected.

@lilimelgar : I assigned the issue to you too for testing and once commented/approved please let me know to create a pull request to merge it into master.

**Comment by lilimelgar** [comment]
@avlisodraude As we commented, it would be useful to add a text that says: "Copy to clipboard". Please let me know when done.

**Comment by avlisodraude** [comment]
**@lilimelgar @jblom:**

A message as been added to the Tooltip letting the user know that on click the query will be saved to the clipboard as shown in the next screenshots:
A pull request has been created in labo-components projects for branch 
_"task/#157-copy-query-params-to-clipboard"_


![Screenshot 2019-01-09 at 14.35.14.png](https://images.zenhubusercontent.com/5a1e745d8a75884b90892ac4/df569f7e-fdc9-4893-bb61-52140e2f0828)

![Screenshot 2019-01-09 at 14.30.23.png](https://images.zenhubusercontent.com/5a1e745d8a75884b90892ac4/93463368-52f1-4e90-82db-aaa63d82aa39)

**Comment by jblom** [comment]
@avlisodraude @lilimelgar I checked this and merged it with master (after a few tiny changes). Please close whenever tested

**Comment by lilimelgar** [comment]
@jblom I tested this on Master branch and it works OK. Sorry to request this so minor issue but, would it be possible to change the color of the text "on click copy to clipboard" so it is more visible? it would also be good to add some space below between the query text and this message U+1F62C

**Comment by avlisodraude** [comment]
@lilimelgar @jblom 

Last comment from @lilimelgar regarding "on click copy to clipboard" message has been done and changes committed directly to master branch from the labo-components.

**What are those changes?**

https://github.com/beeldengeluid/labo-components/commit/97e1b105e72ae26db615cd997befe41d31caf6d8

**Comment by lilimelgar** [comment]
Tested in Master (and in recently deployed production), all OK.
