### ISSUE TITLE
As a scholar, I would like to see the title of the newspaper and the date in the snippet of the result list for the KB newspapers, so I can get a better overview of my results

### ISSUE THREAD

**Issue by jblom** [beeldengeluid/labo-components#159]
@lilimelgar commented on [Thu Jan 18 2018](https://github.com/CLARIAH/wp5_mediasuite/issues/265)

As a user, I would like to see in the snippet of the KB records the following:
-three lines (or as much as allowed by copyright issues) of the content of the article
-Krantentitel
-Datum

Then, in the summary view of the resource viewer (clicking on the "eye" icon next to the result) of the KB newspaper data/articles a list of metadata that includes this metadata from the KB:

Krantentitel
Datum
Soort bericht
Editie
Uitgever
Plaats van uitgave
Verspreidingsgebied

Also, there should be a "OCR" or "Content" preview (longer snippet, if allowed) in the Resource viewer.

---

@lilimelgar commented on [Mon Jul 16 2018](https://github.com/CLARIAH/wp5_mediasuite/issues/265#issuecomment-405282909)

Test on production version July 16 shows that the Krantentitel is displayed in the description field in the metadata snippet. Will this remain like this?

![screen shot 2018-07-16 at 17 15 32](https://user-images.githubusercontent.com/8133228/42766955-0aaf4274-891c-11e8-9c3d-9f48d6b91f08.png)

**Comment by lilimelgar** [comment]
Fixed!
