### ISSUE TITLE
Browser issue: adding collections in Internet explorer

### ISSUE THREAD

**Issue by jblom** [beeldengeluid/labo-components#164]
@lilimelgar commented on [Mon May 01 2017](https://github.com/CLARIAH/wp5_mediasuite/issues/74)

Can’t add collection in Internet Explorer 11 (feedback April 4)

---

@lilimelgar commented on [Sun Jun 25 2017](https://github.com/CLARIAH/wp5_mediasuite/issues/74#issuecomment-310917932)

Also: Collection selector component is not loading selected collection in Chrome.

**Comment by lilimelgar** [comment]
I close this issue and will add to Documentation that the Media Suite is only texted in Chrome.
