### ISSUE TITLE
As a user, I want to see what the fields of the Desmet paper collection mean

### ISSUE THREAD

**Issue by jblom** [beeldengeluid/labo-components#169]
@lilimelgar commented on [Mon Jul 16 2018](https://github.com/CLARIAH/wp5_mediasuite/issues/472)

Add definitions of fields to the Desmet paper collection in the Collection Inspector. Most urgent, add definitions of date fields:

![screen shot 2018-07-16 at 10 18 48](https://user-images.githubusercontent.com/8133228/42748768-aa36a9d0-88e1-11e8-8e8a-6a04305a2402.png)

@jwassenaarbg: Could you please add below the name of the column in Excel that you used for this date fields?: 

Current label | Column from original excel file:
------------ | -------------
coverDescriptionYear => folder | 
coverPeriod => folder | 
groupCoverPeriod => folder | 
gte => folder.coverDescriptionDate | 
Ite => folder.coverDescriptionDate | 
mostSpecificDate => folder | 
subCoverPeriod => folder | 

---

@jwassenaarbg commented on [Tue Jul 17 2018](https://github.com/CLARIAH/wp5_mediasuite/issues/472#issuecomment-405487839)

@lilimelgar I updated the descriptions for this collection view the file here: http://rdbg.tuxic.nl/clariah/eye-desmet-papers2

They will be visible when @jblom updates the config. 

---

@lilimelgar commented on [Thu Jul 19 2018](https://github.com/CLARIAH/wp5_mediasuite/issues/472#issuecomment-406168522)

Good! I put this one on test for me to test later then.

---

@jblom commented on [Wed Jul 25 2018](https://github.com/CLARIAH/wp5_mediasuite/issues/472#issuecomment-407720428)

I published this on test (+ all of todays issues I dragged into the "test column" can be tested on test)

---

@lilimelgar commented on [Wed Aug 15 2018](https://github.com/CLARIAH/wp5_mediasuite/issues/472#issuecomment-413189071)

@jblom I don't seem to get the updated labels mentioned by Johannes in neither version (Test or master branch)...

---

@jwassenaarbg commented on [Tue Aug 28 2018](https://github.com/CLARIAH/wp5_mediasuite/issues/472#issuecomment-416586089)

Can you see the labels now? I was able to view the labels after pulling.

---

@lilimelgar commented on [Wed Aug 29 2018](https://github.com/CLARIAH/wp5_mediasuite/issues/472#issuecomment-416982950)

@jwassenaarbg I can see the dictionary in the Inspector (very useful!). Two suggestions:
(1) Please update the field names to make them more user-friendly
(2) Please update the field definitions

The new data for both updates is included in [this file](https://docs.google.com/spreadsheets/d/1ef2HAWnozgL1Xm4GVTLTYlQVKpdf1r7LZqW0TQVYFPs/edit?usp=sharing).

For later:
-Try to present the metadata in the resource viewer (all data) in a more meaningful order (alphabetically or in logical order depending on the collection).

---

@jblom commented on [Thu Aug 30 2018](https://github.com/CLARIAH/wp5_mediasuite/issues/472#issuecomment-417323955)

@lilimelgar is this done yet?

---

@jwassenaarbg commented on [Thu Aug 30 2018](https://github.com/CLARIAH/wp5_mediasuite/issues/472#issuecomment-417328129)

@jblom I'm working on the suggestions above, not yet finished.

---

@lilimelgar commented on [Mon Sep 24 2018](https://github.com/CLARIAH/wp5_mediasuite/issues/472#issuecomment-424037085)

Tested in test version. The field names have been updated, but the definitions are not there yet. @jwassenaarbg or @jblom: are we going to try to solve the dictionary issue first? (#510).

**Comment by lilimelgar** [comment]
Done, tested in master. @jblom Is this merged in the test version? I cannot see the dictionary there, but  yes in the master branch.

**Comment by jblom** [comment]
@lilimelgar I guess not, but indeed it works on the master, so I'm closing this.
