### ISSUE TITLE
As a scholar, I would like to see the content of some metadata fields in the EYE Desmet film collection properly parsed

### ISSUE THREAD

**Issue by jblom** [beeldengeluid/labo-components#172]
@lilimelgar commented on [Thu May 17 2018](https://github.com/CLARIAH/wp5_mediasuite/issues/418)

The current import of the Desmet film collection has some issues in the parsing of the content of some metadata fields, e.g., actors:
![screen shot 2018-05-17 at 13 54 18](https://user-images.githubusercontent.com/8133228/40175863-d6074ce0-59d9-11e8-958b-32da0b771f48.png).

**Comment by lilimelgar** [comment]
Issue moved to [beeldengeluid/labs-importer #13](https://github.com/beeldengeluid/labs-importer/issues/13) via [**ZenHub**](https://www.zenhub.com/)
