### ISSUE TITLE
As a user, I would like to move in the list of results of the pre-selected bookmarks

### ISSUE THREAD

**Issue by jblom** [beeldengeluid/labo-components#174]
@lilimelgar commented on [Wed Oct 31 2018](https://github.com/CLARIAH/wp5_mediasuite/issues/525)

This issue complements the already implemented issue about navigating within the results list from the resource viewer, i.e., passing to the next/previous result in a list (#479). 

As suggested by Johannes, this issue consists on reproducing the same behavior above for the pre-selected list of bookmarks, which shows when clicking on "Show selected items" (implemented in issue #423).

**Comment by avlisodraude** [comment]
@lilimelgar @jblom 
After 'refining' this issue the ideal behaviour of the bookmarks is:
After going into an 'item details' page and coming back to the Search page the bookmarks should stays still available (currently they are removed when leaving the Search tool).

**Comment by lilimelgar** [comment]
@avlisodraude Yes, as we commented with Jaap, we don't provide any option to move between preselected bookmarks, but when a user clicks on an item and then selects "go back to results" from the resource viewer, they should land in the Pre-selected list again.

**Comment by avlisodraude** [comment]
@lilimelgar @jblom 

After discussing about this issue it was 'agreed' that it won't be implemented.
@lilimelgar : If this issue will not be implemented please close it :-) 
In the meantime moved to the Q/A column
