### ISSUE TITLE
As a scholar, I need extra functionalities for excluding terms in facets when creating my corpus

### ISSUE THREAD

**Issue by jblom** [beeldengeluid/labo-components#175]
@lilimelgar commented on [Tue Jun 12 2018](https://github.com/CLARIAH/wp5_mediasuite/issues/443)

Currently, the list of terms in the Facets (Single Search tool) is based on positive selection, but it is not possible to exclude terms. This is important when creating a corpus.

---

@jwassenaarbg commented on [Thu Jul 19 2018](https://github.com/CLARIAH/wp5_mediasuite/issues/443#issuecomment-406292582)

@lilimelgar The ability to exclude items from facets has been introduced in branch 443, which awaits review from Jaap

---

@jblom commented on [Thu Aug 30 2018](https://github.com/CLARIAH/wp5_mediasuite/issues/443#issuecomment-417331973)

@jwassenaarbg please reimplement this in the updated search API and using a simple checkbox in the UI

---

@lilimelgar commented on [Tue Oct 23 2018](https://github.com/CLARIAH/wp5_mediasuite/issues/443#issuecomment-432255078)

@jwassenaarbg I am testing this in Master, is that correct? or which branch should I use for testing?

---

@jblom commented on [Fri Oct 26 2018](https://github.com/CLARIAH/wp5_mediasuite/issues/443#issuecomment-433321444)

@lilimelgar this was already merged with master, you can check it out.

---

@lilimelgar commented on [Wed Oct 31 2018](https://github.com/CLARIAH/wp5_mediasuite/issues/443#issuecomment-434728616)

Tested in Master with all collections, it works well! The only issue before closing is for @avlisodraude: when the hamburger menu is open in the facet, the buttons don't get resized when the screen becomes smaller, see:

![screen shot 2018-10-31 at 16 20 14](https://user-images.githubusercontent.com/8133228/47798544-e37f4800-dd28-11e8-930f-f69e11dbc907.png)

**Comment by jblom** [comment]
@avlisodraude so check the last comment: there is a tiny issue remaining. The rest of the story has already been done by @jwassenaarbg

**Comment by lilimelgar** [comment]
We entered styling issue in #213
