### ISSUE TITLE
As a user, I would like to move to the next result in my list when I am in the resource viewer

### ISSUE THREAD

**Issue by jblom** [beeldengeluid/labo-components#176]
@lilimelgar commented on [Mon Jul 16 2018](https://github.com/CLARIAH/wp5_mediasuite/issues/479)

Once in the Resource viewer, the user wants to move to the next record in the result list. Allow to move forward, backwards, and go back to the result list.

Specially in the Desmet paper collection, it is important for users to browse the images/documents that belong to a single folder. A complex solution is to add a grid view with all thumbnails (possible to enlarge) of the images belonging to a folder. But a more generic, easier solution, is to add a button on top of the Resource viewer allowing users to move to the next/previous result in the list (for Desmet paper collection users, this means they will have to previously filter by resources in a folder -using facets-, based on the resource of interest).

This updates #112

---

@avlisodraude commented on [Mon Sep 24 2018](https://github.com/CLARIAH/wp5_mediasuite/issues/479#issuecomment-423908400)

@lilimelgar / @jblom :
Issue done in branch named: task/#479-enable-moving-to-the-next-previous-result .
@lilimelgar : Please let me know is this issues works as expected to create a pull request to Master :-) 

---

@lilimelgar commented on [Mon Sep 24 2018](https://github.com/CLARIAH/wp5_mediasuite/issues/479#issuecomment-423950037)

@avlisodraude: tested in Master with all collections, it works well. The only issue is that when users want to go to the result list, they have to click several times on the browser's back button. Suggestion: add the "Go back to results" button. If the user was on result 21 (page 2), bring her/him to Page 2, i.e., use the current stored query.

---

@lilimelgar commented on [Tue Oct 23 2018](https://github.com/CLARIAH/wp5_mediasuite/issues/479#issuecomment-432251884)

@avlisodraude Tested on master with different collections. It is very useful to see now the "Back to results" button, and to go to the current result list page where the user is when clicking the button. The only minor fix to close this issue is to make the "Back to results" button active even when the user reaches the last result in the list, it now gets deactivated when there are no more results:

![screen shot 2018-10-23 at 15 41 20](https://user-images.githubusercontent.com/8133228/47364644-1c407100-d6da-11e8-9ced-ed501bbae83e.png)

---

@jblom commented on [Tue Oct 30 2018](https://github.com/CLARIAH/wp5_mediasuite/issues/479#issuecomment-434199194)

@lilimelgar @avlisodraude  also saw this and fixed this myself before merging, so this should work already. Please test and close

**Comment by lilimelgar** [comment]
@avlisodraude and @jblom  See issue #212 before merging.
