### ISSUE TITLE
Change the color of visited links (search results) in the result list

### ISSUE THREAD

**Issue by jblom** [beeldengeluid/labo-components#177]
@lilimelgar commented on [Thu Jan 18 2018](https://github.com/CLARIAH/wp5_mediasuite/issues/279)

When the user clicks on a result, change the color of the link so s(he) knows that she as visited it already. This complements the issue of showing when an item has been already bookmarked (#419) 

---

@avlisodraude commented on [Wed Oct 31 2018](https://github.com/CLARIAH/wp5_mediasuite/issues/279#issuecomment-434580052)

@avlisodraude @jblom :
Issue done in branch task/#279-change-color-of-visited-links from the labo-components.
Move to Review since a main behaviour should be addressed, when to remove those links from memory (localStorage)?
Options:
- set an expiration date for the items to be removed.
- remove them when changing collection/project ?

At the moment the 'visited items' get removed once a collection is selected (as suggested by Jaap)

Looking forward for your suggestions.

---

@jblom commented on [Wed Oct 31 2018](https://github.com/CLARIAH/wp5_mediasuite/issues/279#issuecomment-434581483)

@avlisodraude so I'd say don't expire the visited links (we could e.g. add a button to the workspace where you can clear the cache per project) and also store them per project, so you can keep track of what you've visited per project.

@lilimelgar what do you think?

---

@jblom commented on [Wed Oct 31 2018](https://github.com/CLARIAH/wp5_mediasuite/issues/279#issuecomment-434634093)

@avlisodraude so let's not relate it to the selected project. Also expire them after a session

---

@avlisodraude commented on [Wed Oct 31 2018](https://github.com/CLARIAH/wp5_mediasuite/issues/279#issuecomment-434726366)

@lilimelgar @jblom :
Done and now the localstorage is not removed unless a session is ended. 
Pull request has been made too :-)

**Comment by lilimelgar** [comment]
Tested in branch task/#279-change-color-of-visited-links with three random collections. The visited links stay until the browser is closed, which was the desired behavior.

@avlisodraude I have two suggestions:
(1) change the colour of the visited links from blue to a lighter colour
(2) also apply the color change to the highlighted words from the search terms, that is, pick a tone of orange that is lighter than the original orange used for the non-visited links. This is to make it clear that the link was visited also in the cases when there is one word in the title which is the same as the search term, see image:

![screen shot 2018-11-13 at 16 11 40](https://user-images.githubusercontent.com/8133228/48422431-f1888c00-e75e-11e8-8288-ad307ef5747a.png)

**Comment by avlisodraude** [comment]
@jblom  @lilimelgar 
I updated the visited colors as requested in @lilimelgar last comments.
Done in master branch (ups!)

**Comment by jblom** [comment]
@lilimelgar if you're ok with it, close this oneeeeeee

**Comment by lilimelgar** [comment]
Nice!
