### ISSUE TITLE
As a scholar, I need to be able to identify in the result list which items I have already bookmarked

### ISSUE THREAD

**Issue by jblom** [beeldengeluid/labo-components#179]
**Acceptance criteria**
- [x] display an icon when an item in the search list (SearchHits) is bookmarked already.
- [x] only show bookmarks related exclusively to the current selected project and NOT all projects the user has created. 
- [x] If no project has been selected nothing should be displayed. 
- [x] On hover a tooltip display a list of groups to which this item belongs. 
- [x] On over the tooltop also shows the amount of annotations made on the item

**Old discussion for context**
@lilimelgar commented on [Thu May 17 2018](https://github.com/CLARIAH/wp5_mediasuite/issues/419)

When scholars are building their corpus, they would like to be able to visually identify which items have been bookmarked already in the result list, so they don't have to inspect them again. This could be solved by adding a "star" icon (bookmark icon) next to the items in the result list, which turns on or off depending on it being or not bookmarked.

---

@jblom commented on [Tue Aug 14 2018](https://github.com/CLARIAH/wp5_mediasuite/issues/419#issuecomment-412843628)

note that an item can be bookmarked multiple times (per different bookmark group), so a "star" would not be a sufficient solution. 

More importantly, I'd say, the bookmark group & annotation model as a whole need to be reconsidered before working on this issue

---

@lilimelgar commented on [Wed Aug 15 2018](https://github.com/CLARIAH/wp5_mediasuite/issues/419#issuecomment-413216914)

When inspecting the result list, it may not be so important to know in which bookmark group an item was included. It helps in the selection just to know if it was bookmarked or not before, perhaps then just automatically checking if it was bookmarked the selected/active user project?

About revising the model, yes! we should work on this. 

The issue is then put in the Icebox.

---

@jblom commented on [Wed Aug 15 2018](https://github.com/CLARIAH/wp5_mediasuite/issues/419#issuecomment-413228035)

good point, but indeed let's wait with a solution after revisiting the model

**Comment by lilimelgar** [comment]
Tested in Master branch with several collections, all acceptance criteria are OK.
