### ISSUE TITLE
As a developer, I need to fix bug in the annotation/workspace API call when user deletes annotations

### ISSUE THREAD

**Issue by jblom** [beeldengeluid/labo-components#180]
@lilimelgar commented on [Wed Aug 22 2018](https://github.com/CLARIAH/wp5_mediasuite/issues/500)

When a user deletes an annotation other bookmarks/segments are deleted (perhaps all related to the same bookmark group). 

---

@jblom commented on [Thu Oct 18 2018](https://github.com/CLARIAH/wp5_mediasuite/issues/500#issuecomment-430882489)

almost done with this one. Will deploy it this morning, so it can be tested. Basically this bug was a sign that it was time to move the complicated "annotation/bookmark assembling & reconsiliation logic" from the client to the server. This means now the annotation API directly calls the search API to reconsile the resource IDs with the metadata. Also the annotation API makes sure the client can directly ask for a list of bookmarks or annotations without needing to further process it.

---

@jblom commented on [Thu Oct 18 2018](https://github.com/CLARIAH/wp5_mediasuite/issues/500#issuecomment-430882724)

Also this meant that the search API needed to have part of the mapping that made sure that the collection data looks handsome on the screen

---

@jblom commented on [Thu Oct 18 2018](https://github.com/CLARIAH/wp5_mediasuite/issues/500#issuecomment-431022064)

@lilimelgar so I've deployed the new stuff on test. You can test it now. If you want to run locally check out these branches:

labo -> no_reconsile
ms -> new_annotation_api

Also I now made deleting a big list of annotations/bookmarks much smoother, since it now takes the browser a single request to delete them all (instead of one for each one selected).

In fact: the old way was really unreliable, since it would happen often that not the entire selection was deleted... (so it required the user to try multiple times)

Anyway. Please test and let me know how it works. I will look a bit more at it tomorrow to make sure it's indeed good enough

---

@jblom commented on [Thu Oct 18 2018](https://github.com/CLARIAH/wp5_mediasuite/issues/500#issuecomment-431025596)

@lilimelgar actually I merged both branches with master, so you can just use that

---

@lilimelgar commented on [Mon Oct 29 2018](https://github.com/CLARIAH/wp5_mediasuite/issues/500#issuecomment-432303220)

@jblom Great to see all these improvements! 

On the test, Master version, there are some initial issues:
See screencast for these two [here](https://drive.google.com/file/d/1QhzQtJifpg7Ymt5Du8e9vwNd2BuxWCaZ/view?usp=sharing):
- [x] When assigning a term (classification, from GTAA) to a Resource, two annotations are created instead of one
- [x] When going back to the Resource to check its annotations, these don't show in the annotation list, but you can see the initial annotation if you click on "Annotate resource". 

I have detected other issues in the Workspace, but perhaps checking this one first would solve the others?

---

@jblom commented on [Fri Oct 26 2018](https://github.com/CLARIAH/wp5_mediasuite/issues/500#issuecomment-433325028)

@lilimelgar thanks for reporting, that one I never noticed. Going to look at it right away

---

@jblom commented on [Fri Oct 26 2018](https://github.com/CLARIAH/wp5_mediasuite/issues/500#issuecomment-433445294)

@lilimelgar been working on this today and might have already solved it (spent quite some time doing another refurbishment cycle, so cleaned up a lot of complicated crap). You could test in the branch annotation_targetting (labo)

Also found why the merging of e.g. classifications (annotation-centric view) does not work properly. Will solve this next week.

---

@jblom commented on [Mon Oct 29 2018](https://github.com/CLARIAH/wp5_mediasuite/issues/500#issuecomment-433904753)

@lilimelgar I've worked on the two things you detected and they should be solved. Also I've fixed the problem with the annotation-centric classification view. Now all related bookmarks/media objects items are properly listed with each classification (other types should work as well)

Please test

**Comment by lilimelgar** [comment]
I tested in the Master branch (updated today, Nov.28) doing these tests:

- [ x ] Bookmark two media objects from the Search list (using bookmark functionality)
- [ x ] Bookmark two media objects from the Resource viewer (clicking on result from search result list) -Problems: see issue b) below
- [x ] Annotate two media objects using all the annotation options
-- [x] One from the Resource viewer (from search result list)
-- [x] One from the Resource viewer (from work space)
- [x] Create segments for two bookmarked media objects
-- [x] One from the Resource viewer (from search result list)
-- [x] One from the Resource viewer (from work space)
- [x] Create segments for one non-bookmarked media object

Issues:
- [ ] **a)** Metadata cards/info is not being displayed for the media objects in the workspace:
![screen shot 2018-11-28 at 08 48 25](https://user-images.githubusercontent.com/8133228/49136613-6b398180-f2ea-11e8-84ee-65e41f47651b.png)

- [ ] **b)** The bookmark button (star) is not getting active when a resource is bookmarked. There are two behaviours here: if the console is open (clean cached is active) the item does get bookmarked, but the button is not showing it.  If the console is not open, the item doesn't get bookmarked (not showing in the result list as such). [See screencast](https://drive.google.com/drive/folders/0B8StOK8IHMiQX0F1akJhLUV2akE)

-[ ] there is a response problem when viewing items from the Workspace. [See screencast](https://drive.google.com/drive/folders/0B8StOK8IHMiQX0F1akJhLUV2akE)

-[ ] Metadata cards/templates are not saving properly (screencast to be added)

-[ ] Targets seem to be duplicated (pending to check):
![screen shot 2018-11-28 at 09 49 31](https://user-images.githubusercontent.com/8133228/49139885-29610900-f2f3-11e8-9b1c-dd69abacdd64.png)

**Comment by jblom** [comment]
@lilimelgar + note to myself: issue b is also reflected in https://github.com/beeldengeluid/labo-components/issues/215

**Comment by jblom** [comment]
@lilimelgar please test this one by checking out branch **issue-180**. I made a pull request (see  #231) for @avlisodraude for this. 

I added a couple of new features:

1. Selecting multiple bookmark groups when bookmarking from the result list:

<img width="889" alt="schermafbeelding 2018-12-10 om 14 49 33" src="https://user-images.githubusercontent.com/917310/49736635-f7548d00-fc8a-11e8-882c-db6ae5b7a998.png">

2. adding/removing multiple bookmark groups from the resource viewer:

<img width="891" alt="schermafbeelding 2018-12-10 om 14 50 06" src="https://user-images.githubusercontent.com/917310/49736721-2834c200-fc8b-11e8-89fe-7362a215207c.png">

**Notes (resource viewer)**: 
- whenever the item is "bookmarked"/annotated the bookmark icon shows 
- renamed the **Bookmark * ** button to **Groups**
- the list now also shows how many bookmarks there are per group.
- it's also possible to deselect groups from the group list
- there is now a red star showing in the **Annotate resource** button, so you can see if you already added an annotation for the resource as a whole (so not the media object, e.g. selected video)
- not totally happy with the styling yet ;-)

3. Added bookmark icon + tooltip to resource viewer that matches the one shown for search hits:

<img width="1314" alt="schermafbeelding 2018-12-10 om 14 50 12" src="https://user-images.githubusercontent.com/917310/49736781-54e8d980-fc8b-11e8-983b-95db95924282.png">

**Comment by lilimelgar** [comment]
@jblom I tested it all! All bugs are solved (duplicated annotations, deleted annotations).

It's very useful to be able to select more than one bookmark group.

Something to improve later is the styling indeed, and also to make the connection with the workspace icons more clear (e.g., in issue #
