### ISSUE TITLE
As a user, I would like to find an icon for the media type

### ISSUE THREAD

**Issue by jblom** [beeldengeluid/labo-components#181]
After discussion (see the thread below) the idea is to make sure the media suite collection configs are easily configurable, so (icons for) the **media type** and **accessibily status** per search result are properly displayed.

**Acceptance Criteria**
- [ ] When searching, a Mediatype icon is always displayed showing the mediatype
- [ ] When searching, an Accessible icon is displayed showing whether or not the media is displayed in MS
- [ ] When browsing bookmarks, the same icons should be displayed.
- [ ] Check whether or not it would be possible to sort on this icon.

**REALLY OLD CONTEXT**
@lilimelgar commented on [Mon Feb 05 2018](https://github.com/CLARIAH/wp5_mediasuite/issues/303)

In the result list of the KB newspaper collection, there are two icons indicating media type: image and unknown:
![screen shot 2018-02-05 at 11 18 23](https://user-images.githubusercontent.com/8133228/35799528-4f50b938-0a66-11e8-9f90-ec62a0bd7a4e.png)
This may be a bit confusing for the users.
Since KB newspapers are both image and text, those two icons could be displayed, or choose "text" since newspapers are mostly textual (from a content perspective, not format-based).

Note: most likely is this due to the fact that the KB newspaper collection indexing is still in progress?

---

@lilimelgar commented on [Mon Jul 16 2018](https://github.com/CLARIAH/wp5_mediasuite/issues/303#issuecomment-405281285)

@jwassenaarbg : after testing on production version (July 16), I see that the icon now is a question mark (non-detected media type). Please check if we should leave this icon, or if this will change, then I can document it.

---

@jwassenaarbg commented on [Tue Jul 17 2018](https://github.com/CLARIAH/wp5_mediasuite/issues/303#issuecomment-405489443)

@lilimelgar Well, technically it is true, since there is no media, it doesn't have a media-type either. We just show links. I will see if we can use another icon for this collection.

---

@jwassenaarbg commented on [Tue Jul 17 2018](https://github.com/CLARIAH/wp5_mediasuite/issues/303#issuecomment-405553551)

@lilimelgar Fixed this probably, but need a test with KB data which is not available in the test version yet. I tested it on DANS (which for me showed a video icon for all items even the restricted ones). Dans also shows the new icon now for results that don't have playout. The changes are pending review from Jaap.

This is the icon I used: https://fontawesome.com/v4.7.0/icon/file-text-o

---

@jwassenaarbg commented on [Tue Jul 17 2018](https://github.com/CLARIAH/wp5_mediasuite/issues/303#issuecomment-405554146)

![screen shot 2018-07-17 at 13 46 31](https://user-images.githubusercontent.com/29273305/42815518-e34e3bb6-89c7-11e8-8c36-8f129d667328.png)

@lilimelgar 

---

@lilimelgar commented on [Wed Jul 18 2018](https://github.com/CLARIAH/wp5_mediasuite/issues/303#issuecomment-405878288)

@jwassenaarbg: I will wait to test in KB later. 
In the DANS screenshot you added, I see a textual icon in the first result: does it mean that the media type is a text (probably a transcript?). If that icon indicates that there is no playout, it should be changed, since the convention used in the rest of the collections is a closed eye:

![screen shot 2018-07-18 at 11 57 12](https://user-images.githubusercontent.com/8133228/42874563-c285f12a-8a81-11e8-83a4-0f2e1213e348.png)
 

---

@jwassenaarbg commented on [Thu Jul 19 2018](https://github.com/CLARIAH/wp5_mediasuite/issues/303#issuecomment-406302393)

@lilimelgar Oke, then I understood your request incorrectly. I have reverted changes I made. When there is no media, just metadata, there will not be any icon anymore, just the closed eye indicating no playout of any media available. For the KB the icon is therefore also removed, as there is no playout of media, just metadata and a link only. If you want we can find an icon for linked media, then a link icon of some sort could be displayed next to the eye.

For example: https://fontawesome.com/v4.7.0/icon/external-link

---

@jblom commented on [Mon Jul 23 2018](https://github.com/CLARIAH/wp5_mediasuite/issues/303#issuecomment-407032922)

I removed the unknown media type (question mark icon), since I also think that it can be confusing

All KB items show the text icon (copied this code from @jwassenaarbg ). 

When configuring the media types per collection, now I view the media type/icon from a scholarly perspective: e.g. KB shows a text icon, even though you can see it as an image. Still not sure though if this is the best approach or the icon should reflect the viewer/browser media format

---

@lilimelgar commented on [Tue Aug 21 2018](https://github.com/CLARIAH/wp5_mediasuite/issues/303#issuecomment-414628240)

@jblom: "Still not sure though if this is the best approach or the icon should reflect the viewer/browser media format." 

How others have solved this:
-Internet archive: the media type of the newspapers is text
-Library of Congress: they assign three types to newspapers:
![screen shot 2018-08-21 at 12 08 53](https://user-images.githubusercontent.com/8133228/44395915-a2560500-a53b-11e8-8236-d51652c0ba5a.png)
-Schema.org: indicates it is a text: https://bib.schema.org/Newspaper

It seems that it makes more sense to go for the user perspective here, and keep newspapers as text. 

Another alternative is to add two types, we could then always assign the viewer/browser format automatically recognized first, and then add the default user type per collection as a second value. Thus, image/text (as two icons, or as a combined icon). This would be also the case of the Desmet paper collection -now shows items as images-.

---

@lilimelgar commented on [Mon Sep 24 2018](https://github.com/CLARIAH/wp5_mediasuite/issues/303#issuecomment-424025879)

@jblom  Tested in test version. Some pending issues per collection:

- [x] Beeld en Geluid AV: Some records don't have automatically detected media type. Is this because they are not digitized? (e.g., ID: 4907842@program).
- [ ] Desmet paper collection: if we follow same idea as with the KB, it should be mostly a text icon
- [ ] Oral history collection: @jwassenaarbg  Please check the issue of all collections having video as media type, it should be detected automatically (some are audio/sound interviews).

**Comment by jwassenaarbg** [comment]
@lilimelgar @jblom 
Its not clear what we actually want here. In the code I found the following note:
"//Note: assigning a media type (to the result data) automatically means it's accessible in the media suite!"

So does this mean that there should be no icon for the majority of the items in Oral History (I thought the eye icon was for showing whether or not it was playable)? Then only for some of the OPEN_ACCESS entries it should show a icon. I think @lilimelgar expects an icon even if its not playable in the mediasuite?

**Comment by jwassenaarbg** [comment]
The Desmet-paper icon is easily changed by changing in the "EYEDesmetPapersPageConfig.js" line 13 (getCOllectionMediaTypes) to 'text' and line 98 (formattedResult.mediaTypes) to 'text'.

Or ask me for the new config :)

**Comment by jwassenaarbg** [comment]
I've also updated the configs for Oral History and the general config if we are going to show an icon regardless of the playout

**Comment by jblom** [comment]
@jwassenaarbg @lilimelgar ok I'd say it's worthwhile to solve this issue altogether, so could you both please make sure that this issue is resolved & described properly?

**Comment by lilimelgar** [comment]
@jwassenaarbg Please check also #207, it was duplicated

**Comment by jwassenaarbg** [comment]
In the Mediasuite two icons are used: first there is the media type icon, and secondly the accessible icon. 

Old situation:
When a playable object was in the result-snippet, its mediatype was used as media icon, and an accessible icon was displayed because there was actual media. 

New situation:
A search snippet should always have a mediatype. This results in the accessible icon always visible. The accessible icon should be dependent on actual playable objects in the result.

Acceptance Criteria:
[] When searching, a Mediatype icon is always displayed showing the mediatype
[] When searching, an Accessible icon is displayed showing whether or not the media is displayed in MS
[] When browsing bookmarks, the same icons should be displayed.
[] Check whether or not it would be possible to sort on this icon.

**Comment by jblom** [comment]
@jwassenaarbg thanks for the update, I've updated the description with your criteria at the top

**Comment by lilimelgar** [comment]
@lilimelgar When testing, also check that the icon shows in the workspace, as it was in #207.

**Comment by jwassenaarbg** [comment]
The workspace does not have the data available to show the accessible icon.

**Comment by jblom** [comment]
@jwassenaarbg checking your pull requests + mapping now: 

To satisfy the criteria of always having two icons, I updated the search API configs a bit: 
- KB default media type = "text"
- EYE film default media type = "video"
- collection_mapping now also maps nisv-catalogue-tv and nisv-catalogue-radio to the NISV config

I'll commit these things later on. I'll let you know

**Comment by jblom** [comment]
@lilimelgar I tested this & merged this into master: could you test this?

**Comment by lilimelgar** [comment]
Tested in Master with all collections, everything OK!
