### ISSUE TITLE
As a scholar I'd like a more helpful message instead of "No results found" after a "failed" search

### ISSUE THREAD

**Issue by jblom** [beeldengeluid/labo-components#183]
**Acceptance criteria**
- [ ] User sees (after a query with no results): "There are no results for your search parameters"
- [ ] The message includes a tooltip that shows the query parameters in the same way as in e.g. the query table in the workspace

**Old issue context**
@lilimelgar commented on [Sun Jun 25 2017](https://github.com/CLARIAH/wp5_mediasuite/issues/89)

In the cases when there are no results, the message should point the user to search tips. Improve message "No results found" by adding: "No results found. You can consult the search tips."

Search tips: to be done... (see issue #90)

---

@lilimelgar commented on [Wed Aug 22 2018](https://github.com/CLARIAH/wp5_mediasuite/issues/89#issuecomment-415063594)

Instead of providing a customized message showing details of why or when there are no results (e.g., no search results for term X, date range X-Y), show a generic message indicating: There are no results for your search parameters. It is also useful to add a tooltip indicating what the search parameters were (e.g., as done in issue #440, showing the query composition/parameters.

**Comment by jblom** [comment]
@lilimelgar @avlisodraude I've added acceptance criteria and changed the user title a bit

**Comment by avlisodraude** [comment]
@lilimelgar @jblom 
Issue done in labo-component branch task/#183-update-no-results-message-in-single-search

What's has been done? Now a default message is displayed to the user in case of no results for current query and a tooltip with the query params used is displayed (reusing workspace query tooltip)

**Comment by jblom** [comment]
@avlisodraude also created the PR for this and checked the code. Looks good. @lilimelgar can you test and close? Then I can merge with master

**Comment by lilimelgar** [comment]
Tested in branch task/#183-update-no-results-message-in-single-search with most collections. It works well! @jblom You can merge with master.

**Comment by jblom** [comment]
@lilimelgar @avlisodraude great, I've merged it with master
