### ISSUE TITLE
As a developer, I need to fix bug in Search tool when switching to histogram type of graphic

### ISSUE THREAD

**Issue by jblom** [beeldengeluid/labo-components#184]
@lilimelgar commented on [Wed Aug 22 2018](https://github.com/CLARIAH/wp5_mediasuite/issues/499)

There is a bug in the Search tool (Master branch, August 22): when one switches to histogram, and enters a new search term, the Search tool turns empty.

See [screencast](https://drive.google.com/open?id=1iJ5SEtZ_jQwTpDaKAfoYEDF_73ihbxr0).

**Comment by lilimelgar** [comment]
Tested with all collections in the Test version. All OK!
