### ISSUE TITLE
As a developer, I could improve the speed of querying the metadata completeness in the Inspector tool

### ISSUE THREAD

**Issue by lilimelgar** [beeldengeluid/labo-components#189]
The Inspector tool (metadata completeness check) requires the completeness query to respond fast; storing the results in the session storage for efficiency.

**Comment by jblom** [comment]
@lilimelgar I think the session storage is already used, but in any case, things could speed up after Mari's changes to the collection analysis code are merged in the search API. (see this pull request: https://github.com/beeldengeluid/labs-search-api/pull/67)

**Comment by jblom** [comment]
Closing because duplicated #422
