### ISSUE TITLE
As a developer, I need to add missing icons for media type to B&G collection when the item is a photograph

### ISSUE THREAD

**Issue by lilimelgar** [beeldengeluid/labo-components#193]
In previous versions, media objects from bg:catalog:"Foto" used to show an image icon indicating the media type:

(e.g., 4937317@program:
![screen shot 2018-02-05 at 11 40 44](https://user-images.githubusercontent.com/8133228/35800537-8a27244a-0a69-11e8-932d-47d2cb2cd2fd.png))

That icon is gone in the current version (3). Please bring it back.

**Comment by jwassenaarbg** [comment]
Updated the config.

**Comment by lilimelgar** [comment]
@jwassenaarbg For testing, which branch did you use for this?

**Comment by lilimelgar** [comment]
Tested in Master, the icon is there for items in bg:catalog:"Foto", and most items with bg:carrierclass:"Foto" (279 157) (some of these belong to a different catalog, and show the Video icon, but with @mwigham we will enter a separate issue for this).
