### ISSUE TITLE
As a developer, I need to delete the spaces between date ranges, so they are shown properly in the Workspace

### ISSUE THREAD

**Issue by lilimelgar** [beeldengeluid/labo-components#195]
In the Workspace, when there is a date range, it occupies more than 10 characters. Since this is the limit for displaying dates in the Workspace, date ranges are shown incomplete, like this:

![Screen Shot 2018-11-07 at 17.27.12.png](https://images.zenhubusercontent.com/5a115fba8a75884b9087ff7a/6d92baad-ab07-45c6-9d3f-5e58db58c584)

This issue consists on either deleting the spaces between the dash, or on augmenting the character limit in the date column, so the dates are displayed complete.

**Comment by avlisodraude** [comment]
@lilimelgar @jblom 
Ready for testing in branch : 
task/#195-format-date-field-in-workspace-bookmark-table 
from labo-components
Issue:
Currently the Date field in the bookmark's table of the Workspace filters by displaying the first 10 characters starting with a number which leaves incomplete dates when there are spaces in between numbers (as shown in Liliana's screenshot). 
The replacement rule has been modified to remove spaces before trunking the date and also removes characters from the date field to avoid issues like displaying text in dates, for example:
1911 ([cir
1993 (comp

**Comment by lilimelgar** [comment]
Tested in Master, with new mappings, project "Testproject-Issues-Liliana" bookmark group Issue 173. Looks Ok. Will be tested further with issue #173.
