### ISSUE TITLE
As a user I'd like to be able to use the 'Quick View' button in the Search Hit

### ISSUE THREAD

**Issue by avlisodraude** [beeldengeluid/labo-components#199]
@lilimelgar @jblom 
Currently the 'Quick view' button in the SearchHits list either doesn't work or breaks the application altogether.

To reproduce: 
Select Newspaper Collection (KB) --  After a search click the Quick view btn. The application breaks with a Javascript error displayed in the console.
Select Dans Oral History -- After a search click the Quick view btn. The pop up doesn't show and no errors are shown in the console.

Cause : The modal uses the resourceId to create an unique identifier, unfortunately some collection's ids are not in a HTML5/Javascript friendly format.

Solved by: Making safeModalId() function 'collection ID independent'.

**Comment by lilimelgar** [comment]
Tested in the master branch. We wait to close it until we can test in the Test version again, to make sure that the cached problem is fixed.

**Comment by lilimelgar** [comment]
I tested in the Test version, it's all OK!
