### ISSUE TITLE
As a developer, I need to fix the problem causing newspaper article titles displaying long text in the KB Newspaper collection

### ISSUE THREAD

**Issue by lilimelgar** [beeldengeluid/labo-components#203]
This bug is in the source data, not in the MS. The bug consists on having very long titles in the KB newspaper collection. A possible solution for solving this in the MS could be shortening them in the MS.

How to reproduce:
-Select Newspaper collection in the Search tool
-Search for the term Sinterklaas, using the "article title" field cluster
-Order the results per relevance

![screen shot 2018-11-13 at 16 18 09](https://user-images.githubusercontent.com/8133228/48469738-edf11580-e7ef-11e8-9abe-52e55db87cef.png)

The result list brings several items with long titles. 

This long titles come directly from Delpher. Example record: http://mediasuite.clariah.nl/tool/default-item-details?id=http://data.bibliotheken.kb.nl/id//ddd-010460629-a0088&cid=kb-newspapers-aggr-xcndj&st=sinterklaas.

**Comment by avlisodraude** [comment]
@lilimelgar @jblom 
Done in branch task/#203-resize-long-titles-in-searchSnippet of the labo-components project.
As agreed with @lilimelgar the maximum number of lines to be displayed for long titles is 6 as shown in the following screenshot.
more than 6 lines shows a '...' icon suggesting more text for the title. If the number of lines is less than 6 nothing done to it.

![Screenshot 2018-11-21 at 15.52.26.png](https://images.zenhubusercontent.com/5a1e745d8a75884b90892ac4/7cda69b5-c39c-4d81-9dfc-00b91eed38a9)

**Comment by jblom** [comment]
@avlisodraude I've merged the code. The CSS solution looks nice. It feels much more straightforward to do it in CSS then to do it in Javascript. Niceeee

**Comment by lilimelgar** [comment]
Tested in the Test version, also with other collections. Nice!
