### ISSUE TITLE
As a scholar, I need to know the details of the collections I am searching on

### ISSUE THREAD

**Issue by lilimelgar** [beeldengeluid/labo-components#204]
This issue applies to: (a) the "Collection selector" in the *Inspect* and *Search* tools, where there is a missing tooltip to bring the user to more detailed information about the collection(s), and (b) to the collection name in the tools *Inspect* and *Search*, where there is a missing pointer to the collection's overall information.

What is the problem?
When scholars use the "Collection Selector", they see a list of collections' names, institutions, and icons. But it is not clear where those collections come from, and what data (media types, time ranges, etc.) are included in those collections. But we have that information. The problem is that that information is disperse in different sources, and we are not sure if the users go there to read that information:
-In CKAN, in textual form, in the Description fields 
-In the Collection pages of institutions (e.g., Google sites))
-In the Inspect tool, where the metadata is described and analyzed
We are currently improving the manual/textual descriptions in CKAN, to include links pointing to all sources of information about the collections.

**Approach**
Simply add two tooltips. These tooltips should automatically include the first two lines (snippet) of the collection description that is written in CKAN, and include a link to the collection's page in CKAN.

**Acceptance criteria**

- [ ] Include a tool tip next to each collection in the Collection selector (see Image 1). The tooltip should include only the first three lines from the description in CKAN.

- [ ] Include a "Read more" button under each collection. The link should bring the user to the CKAN page for the collection. (see Image 1)

- [ ] Include a tool tip AND a "Read more" button in each collection once the collection is selected/opened (see Image 2). Please add this to the Search and the Inspector tools)

**Sketches**

**Image 1: Tool tip in the Collection selector itself**
![screen shot 2018-12-03 at 18 21 28](https://user-images.githubusercontent.com/8133228/49390177-7ba58e00-f728-11e8-9531-21a1a7e4a59f.png)

**Image 2: Tool tip next to Collection title in Inspect tool**
![screen shot 2018-12-03 at 18 27 25](https://user-images.githubusercontent.com/8133228/49390440-3f266200-f729-11e8-9313-e22775c91d7c.png)

**Note of relation to other issues:**
This issue is part of a bigger issue: https://github.com/beeldengeluid/labs-search-api/issues/50. The issue described here indicates what is expected to achieve point No.2 of the acceptance criteria of that issue (No.50).

**Comment by jblom** [comment]
@lilimelgar Clear story, putting it in the backlog.

**Comment by avlisodraude** [comment]
@lilimelgar @jblom :
Issue done in branch task/#204-add-info-to-collection-selector-modal (labo-components)
Goals
In single search:  a tooltip is displayed when hovering a specific collection in the collection selection modal (as shown in the attached screencast video).
Once a collection has been selected the "Set collection" button will display an info icon with the description for the current collection.
In the Inspector tool: Every selected collection will show an info icon that will display the corresponding description.
https://drive.google.com/open?id=1z3pfXrfWbWCnCWPgieU-ghvw1misnXlb
https://drive.google.com/open?id=1TKvsmDwRsEwY7B4O3o8L89H_pZMwZTOB
https://drive.google.com/open?id=1Icu-2m5aJPwS_-fMWxyFh1VuzT868tPX

Collections not in CKAN (Desmet Paper Collection; Kijk - & luistercijfers ; Programmagidsen) don't show the description since this information is retrieved from CKAN (part of organization->description object). 
That information will be displayed once the collections are available in CKAN or we manually set that information in our mappings. 
The branch has not being added to a pull request yet (waiting for some feedback)

**Comment by lilimelgar** [comment]
@avlisodraude, it's taking shape nicely!

I tested in the task/#204-add-info-to-collection-selector-modal (labo-components). 

There are still some issues:

- A style issue that is not fixed after updating the Wp5 master branch and cleaning the cached memory. As you see: the icons appear in the center, while in the videos you sent it is on the right side. Also, the description is extended too long horizontally:
![screen shot 2018-11-27 at 18 04 56](https://user-images.githubusercontent.com/8133228/49098432-215f8580-f26f-11e8-9de7-5625aec20c90.png)

-Another issue to check, is that the descriptions I could read are not the descriptions we would like to have. For example, if you check this collection in CKAN: http://mediasuitedata.clariah.nl/dataset/dans-oral-history, the first lines of that description is the one we would like to have available in the Oral history Dans, not what is there now: "Dans promotes sustained..." I am not sure where this one came from, but it should come from the text in the CKAN link above.

-And lastly, it would be very useful to make the snippets clickable (opening in a new window), so, if users would like to read the full description in CKAN they can go there.

**Comment by lilimelgar** [comment]
@avlisodraude : please check that in this tooltip there is a problem:
![screen shot 2018-12-03 at 18 39 59](https://user-images.githubusercontent.com/8133228/49391133-156e3a80-f72b-11e8-8581-77bef59b5a05.png)

**Comment by jblom** [comment]
@lilimelgar @avlisodraude I've checked, adapted a bit and merged this code into master: https://github.com/beeldengeluid/labo-components/pull/224

@avlisodraude I've moved the ckan URLs to the search API, so you can now read the ckanUrl variable to show them.

**Comment by avlisodraude** [comment]
@lilimelgar  @jblom 
Added 'read more' link in single search tool.
A link component was created for usability and fun :-)
**Branch :(labo-components)** task/#204-read-more-link 
Added as a new branch to avoid merging conflicts since the original branch might be behind master.

**Comment by lilimelgar** [comment]
@avlisodraude Tested in the task/#204-read-more-link branch. Link in the Search tool OK. Pending ToDo: add the same link to the Inspector tool.

**Comment by avlisodraude** [comment]
@lilimelgar  I just updated the branch in the labo-components (ask/#204-read-more-link) so now you should see the 'Read more' link there.
Back to QA. Please comment/ close  after testing :-)

**Comment by jblom** [comment]
@avlisodraude I looked at the code and only moved around the ReadMoreLink component to another package (helpers instead of util).
