### ISSUE TITLE
As a developer, I need to adjust the field cluster selector to make it clearer for users in which fields they are searching on

### ISSUE THREAD

**Issue by lilimelgar** [beeldengeluid/labo-components#205]
Where: In the Search tool, Field cluster selector (image 1, 2, 3, 4).

The problem:
It is not clear for the users what the "All fields" selector mean. Also, for the B&G collection, the subtitles are no longer available

Approach:
Include a separation in the dropdown menu between archival metadata fields and enrichments, so it is clear that "All fields" applies to the metadata fields only (Image 2). Leave the Custom Category as it is, but change label to "Custom field cluster."

Acceptance criteria:
- [x] All collections have an updated label in the dropdown menu from "Custom category" to "Custom field cluster"
- [x] The dropdown for B&G Audiovisual collection is updated (Image 5)
- [x] The dropdown for B&G Television collection is updated (Image 5)
- [x] The dropdown for B&G Radio collection is updated (Image 5)
- [x] The dropdown for EYE Desmet paper collection is updated (Image 6)
- [x] The dropdown for EYE Open Images collection is updated (Image 7)
- [x] The dropdown for B&G Open Images collection is updated (Image 8)
- [x] The dropdown for DANS OH collection is updated (Image 9) 

**Images**
*Image 1*: Current status of drop down menu in the field cluster selector of B&G collection
![Screen Shot 2018-11-19 at 11.18.08.png](https://images.zenhubusercontent.com/5a115fba8a75884b9087ff7a/fc700a6f-5479-4287-9010-a5213716cbb8)

*Image 2*: Current status of drop down menu in the field cluster selector of EYE Desmet paper collection
![Screen Shot 2018-11-19 at 11.24.36.png](https://images.zenhubusercontent.com/5a115fba8a75884b9087ff7a/e25a8da4-73a8-4cc6-bbfb-d7e030d534be)

*Image 3*: Current status of drop down menu in the field cluster selector of Open Images (EYE and B&G) collection
![Screen Shot 2018-11-19 at 11.28.52.png](https://images.zenhubusercontent.com/5a115fba8a75884b9087ff7a/0c7f548c-56d8-4930-8e81-f55e608ea35e)

*Image 4*: Current status of drop down menu in the field cluster selector of DANS Oral history collection
![Screen Shot 2018-11-19 at 11.31.37.png](https://images.zenhubusercontent.com/5a115fba8a75884b9087ff7a/f38a82b2-42ed-4f0b-b0b1-339bca267928)

*Image 5*: Suggested improvement for B&G collections
![screen shot 2018-11-19 at 11 51 52](https://user-images.githubusercontent.com/8133228/48702584-91c43200-ebf1-11e8-981a-01cddb99c36b.png)

*Image 6*: Suggested improvement for EYE Desmet paper collection
![Screen Shot 2018-11-19 at 11.44.18.png](https://images.zenhubusercontent.com/5a115fba8a75884b9087ff7a/75085997-8a1a-4111-b879-b0d680885007)

*Image 7*: Suggested improvement for EYE Open Images Project
![Screen Shot 2018-11-19 at 11.45.06.png](https://images.zenhubusercontent.com/5a115fba8a75884b9087ff7a/85800969-cf3b-4abf-a075-ed6a78ad1f2f)

*Image 8*: Suggested improvement for B&G Open Images Project
![Screen Shot 2018-11-19 at 11.45.43.png](https://images.zenhubusercontent.com/5a115fba8a75884b9087ff7a/d65647e6-423a-48b2-936c-625e0d43e421)

*Image 9*: Suggested improvement for DANS OH collections
![Screen Shot 2018-11-19 at 11.46.20.png](https://images.zenhubusercontent.com/5a115fba8a75884b9087ff7a/abf72213-038a-47a6-a61b-e34281962ae0)

**Comment by avlisodraude** [comment]
@lilimelgar @jblom :
issue done in labo-components branch (task/#205-filed-cluster-selector-adjustements)

Changes done as discussed with @lilimelgar.
screencast at: 
https://drive.google.com/open?id=1vozW4Ysc1HjW6VAu974uWAgexJvVmoUw

mapping files slacked to @jblom  and @lilimelgar as issue-205.zip

**Comment by jblom** [comment]
@avlisodraude @lilimelgar I tested this and merged it with the master (also deployed this on test). I'll send you both the latest mappings, which also include Johannes' Soundbites config.

**Comment by jblom** [comment]
@lilimelgar can this one be closed now?

**Comment by lilimelgar** [comment]
Tested in Master, all good!
