### ISSUE TITLE
As a user, I would like to know from my list of bookmarks which items contain a media object which I can view

### ISSUE THREAD

**Issue by lilimelgar** [beeldengeluid/labo-components#207]
Where: in the Workspace, Bookmark view

What is the problem: as described by a user in Gitter:
"When working in my workspace, I cannot see quickly which items are viewable (and hence segmentable/annotatable), unless I bookmark them as (non)viewable. In the search interface, however, it is possible to see at once whether or not an item is viewable, because it is indicated with en eye-icon. Would it be possible to provide something like this in the work space environment as well?"

Approach:
A simple approach, would be to use the same icon that is used in the Result list (an open/closed eye) indicating when an item can be viewed or not. This icon could be included in the "View" icon of the workspace, for example like this:
![Screen Shot 2018-11-19 at 16.02.27.png](https://images.zenhubusercontent.com/5a115fba8a75884b9087ff7a/6f8fd025-6e0a-430d-9ee0-79f61f8063fc)

Acceptance criteria:
- [ ] There is an icon next to each item in the Bookmark list indicating if the content can or cannot be viewed
- [ ] Optional: if this is in the data, add viewable/non-viewable to the ordering options

**Comment by jblom** [comment]
@lilimelgar looks clear enough. Should be quite easy to fix. Adding it to the backlog

**Comment by lilimelgar** [comment]
Merged with #181
