### ISSUE TITLE
As a developer, I need to update the content of the static pages for V4

### ISSUE THREAD

**Issue by lilimelgar** [beeldengeluid/labo-components#208]
**Note: This issue should be done between November 28 and December 3, 2018**

Where: Main menu, Data page, About page, Contact page.

Approach:
Update the main menu, static text and change a few buttons.

Acceptance criteria

- [x] The main menu is updated
- [x] The home page's messages (box) are updated (see below)
- [x] The About page is updated
- [x] The Contact page is updated
- [x] The Data page is updated:
  - [x] Change text
  - [x] Add new buttons: 
     - [x] See the available collections in CKAN (links to [CKAN](http://mediasuitedata.clariah.nl/))
     - [x] Search & Analyze (links to MS Tool page)

**Content**
All content of the static pages is available [here](https://docs.google.com/document/d/1CAKBFPe1HXxGlIDixBN3o9OO9dd01LDO1NeIPuCkTtc/edit#heading=h.fh5avwshg2td).

The Main page has a box with three message, please delete this message:
![screen shot 2018-11-30 at 15 02 53](https://user-images.githubusercontent.com/8133228/49293794-683cbd80-f4b1-11e8-81ab-d9c5358f3547.png)

**Comment by avlisodraude** [comment]
@lilimelgar @jblom 
content changes done BUT link urls are still missing from the google document. Please update those links to finish updating the static content.
The current changes can be checked at the WP5 project (https://github.com/beeldengeluid/clariah-mediasuite) in branch 
task/#208-update-static-content

@lilimelgar : 
git fetch
git checkout task/#208-update-static-content
npm run prod
Clear cache (console opened)

**Comment by lilimelgar** [comment]
@avlisodraude This issue is almost finished, just one suggestion:
- [ ] In the Learn menu, delete the third item, "Documentation" 
- [ ] In the About page, the CLARIAH logo looks a bit shrunk ;)
- [ ] In the About page, correct the text "CLARIAH is a project funded by the NWO that The" for this: "CLARIAH is a project funded by NWO. The CLARIAH..."
- [ ] In the About page, correct the text "The Media Suite is developed at The Netherlands Institute for Sound and Vision (NISV) as one of the CLARIAH centers." for this one: "The Media Suite is developed at The Netherlands Institute for Sound and Vision (NISV), which is one of the CLARIAH centers."
- [ ] In the Contact page, the link CLARIAH contact should open in a new window
- [ ] In the Contact page, add link to "Learn" pages (documentation)
- [ ] In the Contact page, the link to the Gitter chat rooms should be changed to this: http://mediasuite.clariah.nl/documentation/forum (and open in a new window)

**Comment by jblom** [comment]
@lilimelgar small note: the static content issues should go to clariah-mediasuite

**Comment by avlisodraude** [comment]
@lilimelgar @jblom 
Last changes by @lilimelgar (commented on Dec 3, 2018) are done and push to master branch

**Comment by lilimelgar** [comment]
Tested in Master branch, closing this one, but I added a new issue (#233) for further updates.
