### ISSUE TITLE
As a developer, I need to fix a bug that changes the collection when moving across results

### ISSUE THREAD

**Issue by lilimelgar** [beeldengeluid/labo-components#212]
This issue appears when testing issue #176
Where: In the Search tool

How to reproduce: See also screencast [here](https://drive.google.com/drive/folders/0B8StOK8IHMiQX0F1akJhLUV2akE)
-open the Search tool
-load the television collection of B&G
-search by "Pim fortuyn"
-go to the "last" page of results 
-click on the last result
-click on move to previous result

Acceptance criteria: solve the two bugs in here:
- [x] The collection should not change (see that it changes from Television to Radio)
- [x] When the user is viewing the first result in the last page and clicks on "see previous result", the page should be the one before the last page (see that when moving back to results, it goes to a page that doesn't correspond (it should be the previous before the last page, since I clicked in the last result)

**Comment by jblom** [comment]
@lilimelgar @avlisodraude I tested and see no problem here. The collection stays the same and switching back and forth between the last and the penultimate page seems consistent.
