### ISSUE TITLE
As a developer, I need to fix a bug in the Workspace for two collections which don't display the title and date properly

### ISSUE THREAD

**Issue by lilimelgar** [beeldengeluid/labo-components#214]
Where: In the Workspace, User project: Testproject-Issues-Liliana, Bookmark group: 173

What is the problem:
The B&G Radio collection, and the B&G Television collection, don't display any dates in the Workspace
![screen shot 2018-11-22 at 15 21 42](https://user-images.githubusercontent.com/8133228/48908324-3cdf2080-ee6a-11e8-947e-4aa6f9c12e5c.png)

Acceptance criteria:
- [ ] The radio collection displays the titles properly
- [ ] The radio collection displays the dates properly
- [ ] The television collection displays the titles properly
- [ ] The television collection displays the dates properly

**Comment by lilimelgar** [comment]
@jblom This is a candidate issue for the next sprint (starting with C)

**Comment by jblom** [comment]
@lilimelgar this is a story for me, since the annotation API calls the search API now to fetch the right data. This is not done properly for these two collections. Also moving this one to the search API.

**Comment by jblom** [comment]
Issue moved to [beeldengeluid/labs-search-api #85](https://github.com/beeldengeluid/labs-search-api/issues/85) via [**ZenHub**](https://www.zenhub.com/)
