### ISSUE TITLE
As a developer, I need to handle unexpected characters entered by the user in the search text field

### ISSUE THREAD

**Issue by jwassenaarbg** [beeldengeluid/labo-components#217]
**Story context**
If I enter the search term 'Beatrix (koningin)' in the Media Suite, then all is well.  However, if I forget the closing bracket and enter 'Beatrix (koningin', then the search controls disappear and I need to reselect Search from the toolbar to continue.  Possibly other special characters may also cause problems

**Acceptance criteria**
- [x] Only alphanumerical characters are used for highlighting. This should solve the bug of disappearing controls when Javascript crashes on creating a regex for highlighting
- [x] The highlighting is done smarter by highlighting separate words unless there are quotes around the strings. 

![knipsel](https://user-images.githubusercontent.com/38520885/49086341-96719180-f254-11e8-9b71-077a3102732e.PNG)

**Comment by jblom** [comment]
@jwassenaarbg as agreed: please rewrite this story so:
- the bug is solved
- the highlighting is done smarter (check how other systems do it)

**Comment by jblom** [comment]
merge with #170

**Comment by jwassenaarbg** [comment]
Acceptance criteria:
- [] Only alphanumerical characters are used for highlighting. This should solve the bug of disappearing controls when Javascript crashes on creating a regex for highlighting
- [] The highlighting is done smarter by highlighting separate words unless there are quotes around the strings.

**Comment by jblom** [comment]
@jwassenaarbg thanks, I've put these criteria in the description

**Comment by jblom** [comment]
@lilimelgar I tested & merged this into master. Could you test & close?

**Comment by lilimelgar** [comment]
I tested in Master. The first criteria is OK (i.e., search doesn't crash when non-alpha numeric characters are used). 

The second criteria also works, but there is an extra issue here: 
-If I search for (koe AND varkens) NOT boeren 
the operators are also highlighted, which is not ideal:

![screen shot 2018-12-19 at 11 11 11](https://user-images.githubusercontent.com/8133228/50213762-d1ac3f80-037e-11e9-99ea-1a4111831440.png)

**Comment by jwassenaarbg** [comment]
@lilimelgar @jblom 

Im working on an update for this. AND/NOT/OR are removed from highlighting and since wildcards like * and ? are also supported I'm going to include a regex for that so those terms that match a wildcard are also highlighted instead of literally * or ? characters.

**Comment by lilimelgar** [comment]
I tested in Master, the first acceptance criteria is OK. The second acceptance criteria is being worked together with issue #170.

**Comment by lilimelgar** [comment]
I close this issue since the second acceptance criteria is being taken care of in issue #170.
