### ISSUE TITLE
As a developer, I need to fix the location and styling of the new experimental "linked data" block in the resource viewer

### ISSUE THREAD

**Issue by lilimelgar** [beeldengeluid/labo-components#218]
Where: 
In the Resource viewer there is currently (in the Test version) a new experimental block for simulating how working with linked data would be. To see where the block is, look at Image 1.

What the problem is:
It is an experimental feature which occupies a large part of the Resource viewer page. Users may be confused about what it does. We would like to add it as an experimental feature a bit less prominent and more styled.

Approach:
Do very small fixes to solve only styling issues. The longer term solution will come with the redesign of the Resource viewer (separate project for 2019).

Acceptance criteria:
- [x] Remove the current "linked data" block from the right side
- [x] Place the current "linked data" block on the left side (see Image 2):
-- [ ] Create a new collapsible block called "Related content (experimental)"
-- [ ] Move the current "All data" block to a separate collapsible block, and place it at the end
- [x] Change the "Linked data" block in the following aspects (see image 3):
- [x] Title: rename the block from "Find related content based on these properties" to "Search for related content"
- [x] Order all the metadata fields alphabetically
- [x] Put the fields and their content in a sort of table style. That is, instead of having the field name on top and the content below, put the content of the field in front of the name of the field (as in Image 3).
- [x] Add only the short name of the name of the metadata field, and add a tooltip to the field name with the full name of the field (as it is done in other parts of the Media Suite)

IMAGES

*Image 1: where the block is*
![Screen Shot 2018-11-29 at 14.31.43.png](https://images.zenhubusercontent.com/5a115fba8a75884b9087ff7a/74ece24b-d7c1-4425-9641-d1fbfd90fb61)

*Image 2: How the blocks should look like when the user opens the Resource viewer*
![Screen Shot 2018-11-29 at 14.42.31.png](https://images.zenhubusercontent.com/5a115fba8a75884b9087ff7a/be37501b-9bd7-4f2e-ac32-07c1c2780d33)

*Image 3: How the new block should look like*
![Screen Shot 2018-11-29 at 14.58.39.png](https://images.zenhubusercontent.com/5a115fba8a75884b9087ff7a/43738024-95d3-43c3-be00-45bb1eed5c68)

**Comment by jblom** [comment]
@lilimelgar looks ok. This is an easy fix and should be done on Monday one day before the soft-launch

**Comment by avlisodraude** [comment]
@lilimelgar @jblom 

Last (pending) task for this issue (move All Data section to separated block) is done in a new branch since the original is already merged into master.
**Branch: labo-components**
task/#218-move-all-data-to-separated-block

The block is displayed folded as default in the same fashion as the 'experimental block'.

@lilimelgar : Please check it in that branch (unless merged before you can do it) and close issue if done.

**Comment by lilimelgar** [comment]
Tested in branch task/#218-move-all-data-to-separated-block. 
@lilimelgar : Pending: it was not possible to test with Desmet paper collection, since it doesn't work in this branch.
@avlisodraude, pending to check:
- [ ] in the KB newspapers the blocks show in a different order
- [ ] in the Open beelden collections the blocks show in a different order and the All data is not closed
- [ ] in the OH collection the blocks show in a different order and the All data is not closed
- [ ] in the radio collection the blocks show in a different order and the All data is not closed
- [ ] in the television collection the blocks show in a different order and the All data is not closed

**Comment by avlisodraude** [comment]
@lilimelgar Comment checked and it works ok.
Please test and comment/close the issue :-)

**Comment by lilimelgar** [comment]
I tested this with all collections, it's all OK, except that I could not test the Desmet Film collection since it doesn't work properly in this branch. @avlisodraude Could you please check this with that collection to see why it's not loading?

**Comment by avlisodraude** [comment]
@lilimelgar @jblom  : The issue is related to changes in Desmet Film Collection config (well, actually the data changed). It will be tested when the updated config file is available.

**Comment by lilimelgar** [comment]
@jblom Is the Config file updated for testing this one?

**Comment by jblom** [comment]
@lilimelgar check the oteamdevel channel on Slack, I posted the mappings there

**Comment by lilimelgar** [comment]
Tested in branch task/#218-move-all-data-to-separated-block. There seems to be a problem in this branch which doesn't allow me checking the resource viewer of the Desmet film collection. Since it's related to highlights, @jwassenaarbg: could you please check what the problem is?

![screen shot 2018-12-21 at 09 53 50](https://user-images.githubusercontent.com/8133228/50333663-5f666700-0506-11e9-9f9e-9e45b6d1e254.png)

**Comment by jblom** [comment]
@jwassenaarbg you're checking this?

**Comment by avlisodraude** [comment]
@lilimelgar @jblom 

Regarding @lilimelgar comment (the All data block should have a collapsable option, as the other blocks also have, and it should be collapsed by default.) 

This issue has been solved as requested and a new branch has been created to avoid too many conflicts when merging. 
Also a pull request has been created (replacing the previous which has already been closed) 

https://github.com/beeldengeluid/labo-components/pull/261

![Screenshot 2019-01-17 at 13.17.41.png](https://images.zenhubusercontent.com/5a1e745d8a75884b90892ac4/f554c54f-b170-4252-bb26-80cc99f61ba7)

**Comment by jblom** [comment]
@avlisodraude @lilimelgar I've reviewed the pull request and, because of the "unreactness" of the previous implementation, replaced the JSON component with a nice React one that also offer several convenient configuration options: https://www.npmjs.com/package/react-json-view

I've updated this in the branch (see https://github.com/beeldengeluid/labo-components/pull/261)

Please review this again. After you are both happy, let me know by adding the "tested" label to this issue and placing a comment to me.

**Comment by avlisodraude** [comment]
@jblom @lilimelgar 

I just reviewed that change (Using react-json-view module).
It looks nice and I didn't get any errors while testing with a couple of records:

http://0.0.0.0:5304/tool/default-item-details?id=4144304@program&cid=nisv-catalogue-aggr-full-18-158&st=amsterdam

http://0.0.0.0:5304/tool/default-item-details?id=4098390@program&cid=nisv-catalogue-aggr-full-18-158&st=amsterdam

http://0.0.0.0:5304/tool/default-item-details?id=5180791@program&cid=nisv-catalogue-aggr-full-18-158&st=utrecht

**Comment by lilimelgar** [comment]
This issue has been tested in branch task/#218-update-issue-move-allData-block. All OK. @avlisodraude has sent pull request.
