### ISSUE TITLE
As a developer, I need to do small fixes to the static content

### ISSUE THREAD

**Issue by lilimelgar** [beeldengeluid/labo-components#233]
This issue is a continuation of #208, for working on these edits, after input in WP5 meeting:

- [x] In the Learn menu, "Research projects" is in plural, not in singular
- [x] in the squared window of the main page (with the dots/buttons), change the current message of what the media suite is to this one:
The Media Suite is a research environment of the Dutch infrastructure for digital humanities and social sciences (CLARIAH). It facilitates access to key Dutch audio-visual and contextual collections with advanced mixed media search and analysis tools. 
- [x] in the contact page, make the following changes:
--Troubleshooting? Problems or suggestions in using the Media Suite? | Check our “Learn” pages Or use our Gitter chat rooms
--For research and CLARIAH project-related questions: | 
General questions: mediastudies@clariah.nl
Research coordination: Julia Noordegraaf (J.J.Noordegraaf@uva.nl)
Technical coordination, Netherlands Institute for Sound and Vision: Roeland Ordelman (rordelman@beeldengeluid.nl)
-- Delete "For technical/platform..."
- [x] in the contact page, add a dot to the end of Gitter chat rooms.
- [x] in the Data page:
--Add link to The Netherlands Institute for Sound and Vision: http://mediasuitedata.clariah.nl/organization/netherlands-institute-for-sound-and-vision
--Add link to EYE Film Museum collections: http://mediasuitedata.clariah.nl/group/eye-film-institute-netherlands
--Add link to DANS oral history interview collections: http://mediasuitedata.clariah.nl/dataset/dans-oral-history
--Add link to Collections from the Open Images project: http://mediasuitedata.clariah.nl/group/open-images-project
- [x] In the Data page, change the button "Available collections in CKAN" to: "Available collections"
- [x] in the Data page, change the button "Search and analyze" for "Search and analyze collections"

**Comment by avlisodraude** [comment]
@lilimelgar @jblom 

Static content updated for clariah-mediasuite project in branch __"task/#233-update-static-content"__

**@lilimelgar :**
To test you have checkout (in the clariah-mediasuite project) branch already mentioned and run **git run prod** 
You also must re-start the server via **python server.py** since a json file needs to be updated too.

**Comment by lilimelgar** [comment]
@avlisodraude Tested in Master branch, all OK. One little thing:
In the Tools page, the link to View documentation opens in the same window, while the other links to Documentation or CKAN (outside the MS) open in separate windows.

**Comment by avlisodraude** [comment]
@lilimelgar @jblom 

The branch as been updated to follow the pattern of:
- internal links -- open in the same tab
- external links -- open in a different tab

To test check branch _task/#233-update-static-content_ from the clariah-mediasuite project

**Comment by lilimelgar** [comment]
I tested this branch and it all works as expected: internal pages (documentation) open in the same window, and external pages (e.g., CKAN) open in external windows.
@avlisodraude Please create pull request and close it.

**Comment by avlisodraude** [comment]
@lilimelgar @jblom 
Closing issue as commented by @lilimelgar.
Branch has already been merged with Master.
