### ISSUE TITLE
As a user, I want the Jupter notebook archive browsers to use the same number formatting as the Media Suite

### ISSUE THREAD

**Issue by mwigham** [beeldengeluid/labo-components#238]
See #150 for the format.  already tested that this is possible, one method is to use a locale that has this formatting style, eg. fr-FR

**Comment by jblom** [comment]
Issue moved to [beeldengeluid/labs-search-api #86](https://github.com/beeldengeluid/labs-search-api/issues/86) via [**ZenHub**](https://www.zenhub.com/)
