### ISSUE TITLE
bug: sorting resets after watching a bookmarked item

### ISSUE THREAD

**Issue by jwassenaarbg** [beeldengeluid/labo-components#239]
When in the workspace, with the list of bookmarks, remember the first item. Click to watch the first item and close it, the list of bookmarks has reversed and the first item is not at the bottom.

No specific sorting had been applied, so just go to workspace and then the bookmark list

**Comment by jblom** [comment]
@lilimelgar yes assigned it to @avlisodraude  and put it in the backlog

**Comment by avlisodraude** [comment]
@lilimelgar @jblom @jwassenaarbg 

After checking the issue and trying to reproduce it with the help of @jwassenaarbg we were unable to see it happening so I'm closing the issue.
