### ISSUE TITLE
As a developer, I need to fix a bug when there are no results in the Search tool due to date filtering

### ISSUE THREAD

**Issue by lilimelgar** [beeldengeluid/labo-components#247]
**Where**: In the Search tool

**What**: when using date filters, if the date range is too short, there may not be results. In these cases, users cannot refresh their query or collection. See screencast [here](https://drive.google.com/open?id=1Ny0rgczqJGrDT3ryAjvZLU3zXZtgYzuB).

**Approach**:
Make sure that whenever the user clicks the search button or presses enter in the search bar that the base query (with only the search term) is run again from scratch (now it loads the query from cache)

**Comment by lilimelgar** [comment]
@lilimelgar test

**Comment by lilimelgar** [comment]
@lilimelgar test2

**Comment by lilimelgar** [comment]
@lilimelgar test3

**Comment by lilimelgar** [comment]
@lilimelgar test4

**Comment by lilimelgar** [comment]
@lilimelgar test5

**Comment by jblom** [comment]
@lilimelgar @avlisodraude I added an approach and added this to the sprint

**Comment by jblom** [comment]
@avlisodraude @lilimelgar ok I checked this a bit and got sucked into refactoring a bunch of code: now I'm organising all system messages. The current approach was getting a bit hard to maintain/read.

I'm not done yet, but I want to finish this one myself now. The functionality as discussed is already working, so you could already test this by checking out this branch

**Comment by jblom** [comment]
@lilimelgar the field clusters are now also in the details again. Also now the date is cleared when pressing ENTER or clicking the search button again. To illustrate and as a nice code practice, here's what happens (when clicking search/pressing ENTER again):

newSearch() {
		const q = this.state.query;

		//reset certain query properties
		if(this.state.totalHits <= 0) {
			q.dateRange = null; // only reset when there are no results
		}
		q.selectedFacets = {}; //always reset the facets
		q.offset = 0;
		q.term = this.setSearchTerm.value;

        this.doSearch(q, true);
	}

**Comment by jblom** [comment]
@lilimelgar all is in the master by the way. I'll think about the code freeze over there today. Will let you know. For now it's safe to test the master only
