### ISSUE TITLE
As a developer, I need to reestablish access to the images of the Desmet paper collection

### ISSUE THREAD

**Issue by lilimelgar** [beeldengeluid/labo-components#248]
In all versions (master, Test, and production) access to the Images from the Desmet paper collection is disabled:

![Screen Shot 2018-12-21 at 14.52.17.png](https://images.zenhubusercontent.com/5a115fba8a75884b9087ff7a/c1648235-8a97-4b3a-9c15-38a1e93f6c31)

**Comment by jblom** [comment]
@lilimelgar I created a new certificate for the play-out. B&G videos also would not have been able to play because of this. Did you check this?
