### ISSUE TITLE
As a user I want to switch to the prev/next result and bookmark it from the Quickview modal

### ISSUE THREAD

**Issue by jwassenaarbg** [beeldengeluid/labo-components#250]
@jwassenaarbg commented on [Wed Jan 09 2019](https://github.com/beeldengeluid/x-omgeving/issues/33)

Acceptance criteria:
- [x] The user sees buttons to go to the next or previous searchresult when previewing it in Quickview
- [x] The user is able to select the current result with a visible checkbox in Quickview
- [x] The user is able to use the arrow keys and S (for selection) to do the above actions with his keyboard

I guess I put the buttons in the modal etc and that Eduardo possibly need to move them around with css or something if the location is not right?

**Comment by jblom** [comment]
@jwassenaarbg dank voor het aanmaken, heb hem in de sprint gezet

**Comment by lilimelgar** [comment]
@jwassenaarbg I see that this is functionality works also while testing branch iss_250_quickviewhighlights. I tested in that branch. All OK, nice idea/feature!
If you still need to send a pull request, please do it ;)

**Comment by jblom** [comment]
@jwassenaarbg @avlisodraude I've finally merged this code and made major changes to the single search recipe code (and it's related components). The changes were really needed to make the code more readable & cleaner again. Also this way Frontwise will have an easier time doing the restyling.

@lilimelgar could you test this issue and the other one (#170 ) in the master? When there are bugs, simply report them in new issues. I never want to see these two issues anymore ;-)
