### ISSUE TITLE
As a user of the Media Suite, I would like to see the "all data" text in the Resource viewer wrapped up

### ISSUE THREAD

**Issue by lilimelgar** [beeldengeluid/labo-components#259]
The problem is that when users go to the Resource viewer (All data block) and find a long horizontal text, they scroll to the right but, when trying to scroll to the left (mostly on Mac computers) the behaviour is that the browser sends them to the previous page. A solution is to force the text to be wrapped up in the All data block of the resource viewer.

@avlisodraude Please check if the issue needs further description

**Comment by avlisodraude** [comment]
@lilimelgar @jblom 
Since the 'All Data' block is not formatted with a React module the styling has been 'as a side effect' corrected.
**To test:** @lilimelgar  please check from the Master branch where you can see the block nicely formatted and the issue solved apparently

**Comment by avlisodraude** [comment]
@lilimelgar @jblom 
Since @jblom updated the display of 'All data' block by means of updating the JSON parser this issue is no longer valid.
The issue has been closed after consulting with @lilimelgar
