### ISSUE TITLE
As a developer I need to do small adjustments to the static content of some Media Suite pages, and some small fixes here and there to make things more clear for the users

### ISSUE THREAD

**Issue by lilimelgar** [beeldengeluid/labo-components#262]
This issue includes a list of small fixes to different pages/tools of the Media Suite, to make things more clear to the users:

Acceptance criteria:

**In the homepage**
- [x] First news item in the box says what the Media Suite is and points to read more about the Media suite, since About page changed content, update the link to go here: http://mediasuite-test.rdlabs.beeldengeluid.nl/documentation/faq/what-is-it
- [x] Second news item in the box should point to entire blog instead of last post (it's not handy to update this all the time), so, use this link instead: https://clariah.github.io/mediasuite-blog/
- [ ] Resize hamburger menu main menu

**In the Search tool**
- [x] In the Field cluster selector, when creating a Custom field: it should show fields order alphabetically, and allow searching for field names (add search box as it is done when creating a new facet)
- [ ] Sometimes the switching between types of charts takes long and the lines look a bit stuck. Could a way to solve this be adding the "loading results" message?
- [x] In the preview of the resource (when clicking on the icon next to each result in the list) there should be a link to open the Full resource viewer
- [x] Currently, to create a new facet there is a label that says "New" (see image 3). Change that label so it says: "Add a new facet"
- [x] The new facet creator opens in a pop-up window. Change static text in the pop-up from "Create new aggregation" to "Create a new facet".
- [x] The new created facets appear now at the bottom of the existing facets, it is better for the users to have the newly created facets on top, so the user can see immediately the efects of having created a new facet
- [x] When users save a query using the "Save query" button, it would be ideal if the pop-up window allows the user to: (1) see which the parameters are  -this is not there but could be reused, (2) assign a name to the new query and save it, -this is there (3) see a list of previous queries (with a header that says: "Saved queries in this User project", -just add this header (4) delete or open the previously saved queries -this is possible, nothing to do, and (4) it also shows to which User project the user is saving the query -this is new to be done, not there.
- [x] Also in the save query menu: Once a query is saved, the user gets a confirmation message that it is saved in the Workspace (name of user project)
- [x] In the Search tool, change the text in the search box here below, Instead of "search" write: Search (see "how-tos" in the help "?" button):
![screen shot 2018-12-11 at 15 42 57](https://user-images.githubusercontent.com/8133228/49809421-22a8ac00-fd5f-11e8-9191-15a0c2898159.png)

**In the Inspector tool**
- [x] Histogram. Hoving mouse over bars in histogram shows pop-up per year with correct information in absolute and relative values (total, present, missing), the numbers should be shown with separator
- [ ] Even after cleaning cached data, information from the first field selected persist for several minutes/refresh tries when selecting another field. Because of this, some numbers look as if they were not updating properly when changing X value in the same field, or even when switching fields (it always shows the same value), that is (e.g., records that do not contain the analysis field), it is clearly a cached issue since the data updates correctly after "cleaning/refreshing" several times. Is it possible to optimize this?

**In the Workspace/projects/create user project, see image 1**
- [x] /workspace/projects/create. Change the text "This is a private project that is only visible to you and your collaborators" for this: "This is a private user project that is only visible to you"
- [x] The tick box in "This is a private user project that is only visible to you" appears checked by default and cannot be unchecked
- [x] /workspace/projects. Add (forthcoming) to the checkbox "Show only my projects", or keep tick box ticked by default -see how this is fixed in issue 262
- [x] /workspace/projects. The bookmark icon is gone from the User project menu

**In the Workspace, resource viewer that opens from there"
- [x] It should have a link/option to open in a separate window

**Resource viewer Newspaper collection**
- [x] Please fix this little thing in the Newspaper resource viewer, instead of "application?" it should say "View resource" (Image 2)

**Images**
_Image 1_
![screen shot 2019-01-22 at 11 50 03](https://user-images.githubusercontent.com/8133228/51531120-e1ff8080-1e3c-11e9-9301-357211f72a72.png)

**Image 2**
![screen shot 2019-01-23 at 16 43 28](https://user-images.githubusercontent.com/8133228/51619635-0f2d5b00-1f31-11e9-9cd6-14845d6ebff8.png)

**Image 3**
![screen shot 2019-03-05 at 12 21 04](https://user-images.githubusercontent.com/8133228/53802110-42580680-3f41-11e9-86d2-e7f83d07a177.png)

**Comment by jblom** [comment]
@lilimelgar could you update the criteria for this story (check the comments please) and then assign it in this sprint to @avlisodraude ?

**Comment by lilimelgar** [comment]
@jblom I updated this issue with all the small fixes I found during the full test of the test version (master branch) which will improve the "usability"/understanding of the Media suite for the users. Because the list is longer now, please check if this should be split into smaller issues.

**Comment by avlisodraude** [comment]
**@lilimelgar @jblom**
 
This issue has been done by splitting it in several issues for both projects (labo-components,/clariah-mediasuite)
 
Each new issue has been added as a Dependency for this one. 

**From the checklist (Acceptance criteria) the only points not addressed are:**

- [ ] Resize hamburger menu main menu (Homepage)
- Not clear what needed to be done.
---
- [ ] Sometimes the switching between types of charts takes long and the lines look a bit stuck. Could a way to solve this be adding the "loading results" message? (Search Tool)
- Unable to reproduce.
---
- [ ] Even after cleaning cached data, information from the first field selected persist for several minutes/refresh tries when selecting another field. Because of this, some numbers look as if they were not updating properly when changing X value in the same field, or even when switching fields (it always shows the same value), that is (e.g., records that do not contain the analysis field), it is clearly a cached issue since the data updates correctly after "cleaning/refreshing" several times. Is it possible to optimize this? (Inspector tool)
- Unable to reproduce. 
---
**@lilimelgar** In every pending case please create an issue/bug with a description on how to reproduce it.

**Comment by jblom** [comment]
@lilimelgar @avlisodraude I've moved this issue to the new sprint. Please resolve & address this one again to make sure we can finish this one

**Comment by lilimelgar** [comment]
From the comment above:
-Hamburger menu issue: appears to be solved
-Switching between types of chart: issue persists, opened in a separate issue
-Cached data issue in Inspector: not able to reproduce again

Closing this one then
