### ISSUE TITLE
As a developer, I need to improve the usability of the functionality for creating new bookmark groups

### ISSUE THREAD

**Issue by lilimelgar** [beeldengeluid/labo-components#264]
In the Search tool, when the user selects some items and tries to save them in a new bookmark group, s(he) finds the option to create that new group, but may not understand that hitting enter actually creates the group. The user may hit "save" instead, but in this case the bookmark group is not actually created.

**Acceptance criteria**:
- [x] If the user has entered some name in the New bookmark box, hitting the Save key saves the new bookmark group and any other bookmark group selected in this window.
- [x] if the user hits enter in the input field, the bookmark group is added to the list AND selected at the same time (now it's not selected)

**Comment by avlisodraude** [comment]
**@lilimelgar @jblom** 
Issue for labo-components project done in branch:
_issue/#264-create-new-bookmark-group-enhancements_

### What's been done?
- If the user has entered some name in the New bookmark box, hitting the Save button saves the new bookmark group and any other bookmark group selected in this window.
-  if the user hits enter in the input field, the bookmark group is added to the list AND selected at the same time (selected by default)
- Input validation for new group. No empty name field allowed for new groups.

###Screencast
https://drive.google.com/open?id=1UEciFYVZOcjX23aJxH_YzAncRTYDxMD_

**Comment by avlisodraude** [comment]
**@jblom** 
Pull request created for this issue:
_https://github.com/beeldengeluid/labo-components/pull/389_

**Comment by avlisodraude** [comment]
**@jblom** 
Validation for duplicated group name added. IE, now a name already in the groups list won't be accepted (case insensitive)

**Comment by jblom** [comment]
@avlisodraude alright I've checked the code, tested and took the opportunity to clean up & optimise the code (quite) a bit.

I did not change anything to the functionality since it was fine :-)

Will deploy this on test, so @lilimelgar can test it when in the office
