### ISSUE TITLE
As a user, I would like to see a "loading results" message when the chart is taking long to be processed

### ISSUE THREAD

**Issue by lilimelgar** [beeldengeluid/labo-components#266]
Where: In the Search tool, mostly with the KB newspaper collection. 

Problem: When switching between relative/absolute, and histogram/line chart, the graphic takes quite some time to be processed. 

Approach: users should see a "Loading results message"

**Comment by jblom** [comment]
@lilimelgar @avlisodraude closing this since it is a duplicate issue
