### ISSUE TITLE
As a user I'd like to fix bug when clearing the localStorage from my browser

### ISSUE THREAD

**Issue by avlisodraude** [beeldengeluid/labo-components#269]
**Issue:** 
Fix bug when clearing the localStorage from my browser while clicking the OPEN link in the 'Compare queries' table. 

The following screencast shows the issue :

https://drive.google.com/open?id=1xFC8XSui5CU8iY30GmynrIgUy0FguhLd

**Comment by avlisodraude** [comment]
@jblom 
Issue solved in labo-components branch __issue/#269-bug-when-clearing-localstorage-for-activeProject__ 

**What's been done?**
Now every time in the project's table a project is selected via row links (name, description, OPEN btn) the 'activeProject' is loaded into localStorage. Also in the 'single search tool'  the condition 'this.state.activeProject' to load a query has been removed since not always a project has been already selected, ie, when copy and pasting a query.

**Screencast showing both cases working:**

https://drive.google.com/open?id=1jBM4FRuDLztxTN6r5qPk7xWaU-Jy8ORm

**Comment by jblom** [comment]
@avlisodraude @lilimelgar this works fine, the only thing that is now unclear for the user is that the active project changes when you click on one in the workspace. Maybe it's good to create a separate issue where this is made clear (by e.g. highlighting the active project in the project table with a different colour)

I did merge the code though. So this one is closedddd
