### ISSUE TITLE
As a user I want to solve a bug in the comparative tool when switching to relative values solved 

### ISSUE THREAD

**Issue by avlisodraude** [beeldengeluid/labo-components#272]
**Issue:**
 Bug in the comparative tool when switching to relative values.

In some cases (depending on the query) when a user compares a query and switch to relative values in the graph an error stops the current page. 

**Cause:**
When date ranges are incorrect (impossible dates or so) a min year is set via the collection configuration getMinimunYear(). In the exact case screencast below the min year is set to 1850. But in the example used in the screencast the issue arises because there are records with end dates up to 01-01-2998.
To solve it more care will be taken regarding date ranges. 

Screencast showing the issue:

https://drive.google.com/open?id=1bYzPCtuHzbx2yUfMqvwt36qtEwnvBSA8

**Comment by avlisodraude** [comment]
@lilimelgar @jblom 
Issue solved along with issue https://app.zenhub.com/workspaces/main-board-5bd99e4e4b5806bc2befbe27/issues/beeldengeluid/labo-components/166
This ticket is for references only since the work has been done in labo-components branch 
task/#166-Add-histogram-to-comparative-tool
 which related to issue 
https://app.zenhub.com/workspaces/main-board-5bd99e4e4b5806bc2befbe27/issues/beeldengeluid/labo-components/166

**Comment by lilimelgar** [comment]
Tested together with issue #263 (same branch), all OK (except small fix for triplicated dates in query box reported there in 263). Otherwise, ready for pull request.

**Comment by avlisodraude** [comment]
@lilimelgar @jblom :
Issue solved as part of #166
