### ISSUE TITLE
As a Media Suite stakeholder, I would like to store the static pages at the Internet archive, so I can see how it has evolved over time

### ISSUE THREAD

**Issue by lilimelgar** [beeldengeluid/labo-components#273]
For presentation purposes, looking at the history of the Media Suite, it would be useful to have the site archived by the Wayback machine:
https://web.archive.org/save/http://mediasuite.clariah.nl

To do this, Jaap suggested:

User-agent: *
Disallow: /
in robots.txt :wink:
we could change this to allow indexing the static pages

@jblom  Not sure if this should be an issue here (in which repo), or a ToDo somewhere else...

**Comment by jblom** [comment]
Issue moved to [beeldengeluid/clariah-mediasuite #15](https://github.com/beeldengeluid/clariah-mediasuite/issues/15) via [**ZenHub**](https://www.zenhub.com/)
