### ISSUE TITLE
As a collection owner, I need users of the media suite to sign a consent form when logging into the media suite (for the first time), so legally users should be aware of the rules

### ISSUE THREAD

**Issue by jblom** [beeldengeluid/labo-components#282]
**Acceptance criteria**
- [x] get the text to be displayed in the consent form
- [x] when a user logs in show the consent form in a pop-up
- [x] the user must press agree before he can continue to the media suite 
- [x] consent is stored in a cookie, so the user does not have to agree every time

**Comment by avlisodraude** [comment]
**@lilimelgar @jblom** 
Issue done in 2 branches of the clariah-mediasuite project  (to show possibilities like full modal blocking all content && a top banner message blocking only menu options)

**Branches:**
https://github.com/beeldengeluid/clariah-mediasuite/tree/issue/%23282-user-consent-form

https://github.com/beeldengeluid/clariah-mediasuite/tree/issue/%23282-user-consent-form-v2

**Main considerations to this approach:**
1. user enters mediasuite.clariah.nl and can click on Learn pages, Data page, About, Contact

2. when the user clicks on Tools, Workspace, or Login the Login dialog appears
3. You have two options here:
   1. integrate the tick boxes with acceptance of the two items (1.terms of service + 2.have read privacy statement) in the Login windows, or
   2. make the dialog with two tick boxes appear before or after login

**What's been done?** 
To implement this consent modal a small but really popular library has been used (https://cookieconsent.insites.com/).
The library has a lot of configuration already implemented and also allows a lot of custom config and stylings (like both branch show).

**To consider:**
The texts in the modal are test but can be easily changed as well as layout considerations like colors and font stylings. The link to the 'Ream more' is the one provided by @lilimelgar as part of the requirements.

**To test:**
In the clariah-mediasuite project test in both branches (mentioned above).
Please make sure cache is been cleaned. To be sure what's expected hereby I attach 2 screencast with the consent forms.

https://drive.google.com/open?id=1W_Ft56PVyGndJEP1PMcCrB40ZFKtohUq

https://drive.google.com/open?id=1zkD6Of6ERzno9GRTFjdB3kMtWvw_el8b

For final texts and required changes to texts and layout please leave your comments here :-)

**Comment by lilimelgar** [comment]
@roelandordelman: could you please be the reviewer of this issue? The approach taken by @avlisodraude is to overlay a box with the "agree" button (and the link to the tests) which impedes the user to see the entire Media Suite menus until s(he) agrees. He uses this cookie approach: https://cookieconsent.insites.com/.

**Comment by lilimelgar** [comment]
@avlisodraude After discussing with Jaap, we would like to suggest that the text of both documents (terms of use, and privacy statement) has to be scrolled down and the "agree" button should be in the end. We can discuss the acceptance criteria again, for now moving it to "in progress".

**Comment by jblom** [comment]
@lilimelgar @avlisodraude @roelandordelman let's update the text of this story to reflect what we've decided

**Comment by avlisodraude** [comment]
@roelandordelman 
cc: @lilimelgar @jblom 

Issue updated based on last comments:

**What's been done?**
A fresh new branch has been created out of Master to avoid conflicts based on quite a few new updates and the old 'working' branch has been removed. The new branch in the clariah-mediasuite project is named: _issue/#282-user-consent-modal_

**Functionality**
After the user logs in a pop-up/modal is displayed letting him/her know that he/she must accept the agreements in order to make use of the MediaSuite.
She/He must explicitly check all boxes to continue otherwise a warning will be displayed until all checkboxes are properly selected.
Once the form is accepted a cookie is set in the user's browser with a expiration date of 6 months.

**To be done**
The final text must be provided by @roelandordelman. 
Currently the text used as an example is the one in the documentation page http://mediasuite-test.rdlabs.beeldengeluid.nl/documentation/privacy-statement.


**Screencast with the current implementation**
https://drive.google.com/open?id=12Gsw2gQ0GqaNPYOjDxiQyR61x9kJDZDQ

**Comment by avlisodraude** [comment]
@roelandordelman @jblom @lilimelgar 

Issues updated in clariah-mediasuite project, branch:
_issue/#282-user-consent-modal_

Text based on the last version available (19-03-2019) in Google Drive at (https://docs.google.com/document/d/1iUmvw3kmXZyjK1UEgYdDuO8WkQ645qiH0MksE13LnU8/edit?ts=5c8a67bf#heading=h.ha22z8wxw6fv)

At the moment the consent pop-up is shown only after the user logs in and the cookie is set for a 6 months period after accepting.

**Comment by jblom** [comment]
@roelandordelman @avlisodraude is going to send now the text to Corne and some screenshots how it looks in the media suite. I've merged the code, which looked good. Will deploy it on test too today.

**Comment by jblom** [comment]
@lilimelgar @roelandordelman ok it's now also deployed on test. The rest of the code is still the same so it should not influence your tests @lilimelgar ;-)

![Schermafbeelding 2019-03-25 om 14 18 32](https://user-images.githubusercontent.com/917310/54922698-fcbba780-4f08-11e9-81f2-7e8641fea205.png)

![Schermafbeelding 2019-03-25 om 14 18 39](https://user-images.githubusercontent.com/917310/54922707-034a1f00-4f09-11e9-8269-dab04deb667c.png)

**Comment by lilimelgar** [comment]
Tested in production. All OK 👍  @avlisodraude: the updated text is also copied to the documentation: http://mediasuite.clariah.nl/documentation/privacy-statement
