### ISSUE TITLE
As a developer, I need the word timings to be in the ASR index as well, so on the front-end we can do wonderful things

### ISSUE THREAD

**Issue by jblom** [beeldengeluid/labo-components#284]
- [x] The ASR1BestImporter is updated to also extract the 1Best ctm file with word times
- [x] The words and word-times are read into an array
- [x] The importer check if the length of the word and word-times array is the same
- [x] The importer logs in case there is an error

**Comment by jblom** [comment]
@jwassenaarbg could you please add a test plan in the comments here, so I can review it?

**Comment by jwassenaarbg** [comment]
@jblom Testplan:
- [ ] Check the code in the pull request (https://github.com/beeldengeluid/rd_infra/pull/1)
- [ ] Search in the Mediasuite using the ASR cluster, and inspect some results. If there is a "words" key in layer__asr, there should also be a "wordTimes" key.

**Comment by jblom** [comment]
@jwassenaarbg ok thank you. @mwigham could you review this one? I've already sort of checked it, so it's nice if you could as well.

**Comment by mwigham** [comment]
Did some test searches in the NISV collection and the Television and Radio collections, with various search terms, then picked out some random results. They all had both words and wordTimes.  I also ran a query on the cluster and the number of items with the wordTimes field is the same as the number with the words field, that also gives some confidence ;)

**Comment by jblom** [comment]
@mwigham thanks for testing as well. Also the code was merged into master. Closing this one
