### ISSUE TITLE
As a user, I would like to see a label in the Comparative search tool for the X axis in the graphic

### ISSUE THREAD

**Issue by lilimelgar** [beeldengeluid/labo-components#285]
To facilitate research, all charts in the Media Suite should have a title, a label for X axis, and a label for Y axis. At this moment, the Compare tool's chart misses an X axis label. Since the date field changes per query, add a generic label such as this:

Year (selected date field varies per query)

**Comment by jblom** [comment]
@lilimelgar put this in the backlog.

**Comment by avlisodraude** [comment]
@lilimelgar @jblom 

Issue done for labo-components project in branch __"issue/#285-add-label-xAxis-in-compare-tool"__

**Test**
git checkout issue/#285-add-label-xAxis-in-compare-tool
npm run prod
Make sure that browser CACHE is cleared (better run it with the console tool opened)

**Screencast**
Expected result:
https://drive.google.com/open?id=1QWP_YgQ5x1gLTX6P6YTIVYoRzFbKeMcs

@lilimelgar : Please check issue in the already mentioned branch and comment to make changes or create a pull request.

**Comment by jblom** [comment]
@avlisodraude this works fine, could you please make a PR? 

@lilimelgar this is a super small issue, so merging this right away if you're ok with the screencast, ok?

**Comment by jblom** [comment]
@lilimelgar @avlisodraude merged this one as well, so it will be in the release I'll do in a bit
