### ISSUE TITLE
As a user, I would like to see more clear terminology about "highlights" in the results preview

### ISSUE THREAD

**Issue by lilimelgar** [beeldengeluid/labo-components#289]
Where: Search tool, result list, preview
What the problem is: terminology in the preview is not consistent with the search tool

Recommendation:
- [x] Instead of using current static text: "Highlighted term(s) in metadata" use: "Matching terms in archival metadata"
- [x] Since the user can get a message of zero matches in the metadata (but we know there are matches in the ASR or OCR), the message for collections which have enrichments (ASR or OCR) should say: “No matches in the archival metadata, matching terms found in the automatic enrichments”
- [x] only applies to the KB newspapers: since the OCR is not visible, see if we can change static text: “no highlights in metadata” for something like 
    Matching terms: none in archival metadata (see OCR in KB Delpher)

Note: this is an enhancement to [#170](https://github.com/beeldengeluid/labo-components/issues/170)

**Comment by jblom** [comment]
@lilimelgar good & simple issue. Put this in the backlog

**Comment by avlisodraude** [comment]
@lilimelgar @jblom 

Issue done for labo-components project in branch __issue/#289-modify-static-texts__

**Test**
git checkout issue/#289-modify-static-texts
Include KBNewspaperAggrConfig.js file (supplied via Slack)
npm run prod
Clear CACHE in browser (better keep console tools opened)

**Screencast**
The recommended point (3 checkboxes) changes can be seen in:

https://drive.google.com/open?id=1MN-DDn2YMx_yHrwDIJ7l4qQ49u_FmRaP

**Comment by lilimelgar** [comment]
@avlisodraude  Tested in branch issue/#289-modify-static-texts.

It all works well, just two things before pull request:
- [ ] correct: "enrichment**s**" should be in plural.
- [ ] I forgot to request to add "archival" to this sentence: "# match(es) in archival metadata"

**Comment by avlisodraude** [comment]
@lilimelgar @jblom 
Changes to texts done according to last comment done by @lilimelgar.
Changes have been committed (to the same branch). 

**Where are those changes:**
https://github.com/beeldengeluid/labo-components/commit/497f936a816928138e15f5e0a6a8e4588cbd55be

**File affected:**
app/components/search/SearchSnippet.jsx
Quick Reference: check lines 107-110

**@lilimelgar:** Issue back in Q/A waiting for approval to make a pull request.

**Comment by jblom** [comment]
@avlisodraude ok I tested & merged this one. I've updated the quick viewer a bit, so it only displays a single message in case there are no highlights (for KB):

![Schermafbeelding 2019-03-13 om 11 42 40](https://user-images.githubusercontent.com/917310/54273113-75c01400-4585-11e9-9703-4f7b7759c9a7.png)

![Schermafbeelding 2019-03-13 om 11 43 48](https://user-images.githubusercontent.com/917310/54273118-78226e00-4585-11e9-9f65-1383a4fbf0c1.png)

I'll send you the updated mapping again (which includes the adapted message for KB)
