### ISSUE TITLE
As a developer, I need to check why the highlights of matching terms from the Open Beelden collections are not showing properly

### ISSUE THREAD

**Issue by lilimelgar** [beeldengeluid/labo-components#290]
(draft issue, detected when testing [#170](https://github.com/beeldengeluid/labo-components/issues/170) with the two Open Beelden collections:
- Highlights don’t seem to work with the Open Images Eye collection, they don’t show
- Issue with highlights for the Open images B&G collection: search only goes to metadata, thus, all records should have a highlight, but some don’t show any

Note: not sure what the problem is and if this should be in this repo...

**Comment by jblom** [comment]
@lilimelgar same as the other. This is a nice job for @jwassenaarbg :-)

**Comment by jwassenaarbg** [comment]
Unable to reproduce both on the current master. What were your queries that resulted in the behaviour? @lilimelgar

**Comment by lilimelgar** [comment]
I tested this again in the latest version of the master today, and the issue is not there anymore :)
