### ISSUE TITLE
As a scholar, I want to be able to see the curated segments of programs, so I can navigate through those while watching a program

### ISSUE THREAD

**Issue by jblom** [beeldengeluid/labo-components#295]
This previous list of "tracks" shown for certain items in the resource viewer are really flawed and do not properly reflect a playlist of media objects related to the main resource/item (e.g. tv program).

Now it's time to properly fix this half finished implementation and instead show a useful list of media objects and/or media segments (note: a media object can have 1 or more curated segments; for B&G these are mostly present for news programs)

**Acceptance criteria**:
- [x] Curated segments can be clicked to skip through the video
- [x] For B&G, "Schone inlas" carriers (raw materials) are hidden, but the user can see which they are

**Comment by jblom** [comment]
@lilimelgar @avlisodraude I've already merged the code for this story and story #270 into master since it's important that this code gets tested really well and becomes part of the next release.

See issue #270 for the test plan for that issue. For this issue, please test the following:

- [ ] the track list is gone forever and instead you see a nicer collapsable play list next to the player (see images below)
- [ ] in case there are segments, test if you can use it to jump to that moment in the video
- [ ] test if you can play any "raw materials" (should not be possible)
- [ ] the collapse component was updated. Please test if it still works in all places in the media suite
- [ ] test if play-out still works for all collections 

**List of items that have an interesting playlist (for testing)**
- http://localhost:5304/tool/default-item-details?id=FLM77223&cid=eye-desmet-films&st=werk
- http://localhost:5304/tool/default-item-details?id=482379@program&cid=nisv-catalogue-aggr-full-18-158&st=%22openbaar%20vervoer%22
- http://localhost:5304/tool/default-item-details?id=50263@program&cid=nisv-catalogue-aggr-full-18-158
- http://localhost:5304/tool/default-item-details?id=5313446@program&cid=nisv-catalogue-aggr-full-18-158&st=aardkloot

**Imagery of solution**
<img width="1203" alt="schermafbeelding 2019-02-25 om 14 16 51" src="https://user-images.githubusercontent.com/917310/53340438-53819180-3909-11e9-880a-9a2ce54d0356.png">
<img width="1166" alt="schermafbeelding 2019-02-25 om 14 17 22" src="https://user-images.githubusercontent.com/917310/53340447-567c8200-3909-11e9-9fc8-cd9f84aa4878.png">

**Comment by jblom** [comment]
@lilimelgar @avlisodraude also deployed the latest master on test right now

**Comment by lilimelgar** [comment]
@jblom I tested in the Master. Nice that the tracks are now more clearly organized! It all works as expected. I just have two things to suggest, and one strange thing that am not sure if it's related:

1. The annotations only show for the active carrier. However, it is difficult for a user to remember to which carrier the annotations were made to. Isn't it possible to show by default all user annotations and when clicking on them jump to the carrier and not the other way arround?

2. In this video, there is also a playlist with the curated segments, but they don't show in correct order (time-wise):

![screen shot 2019-03-06 at 11 14 48](https://user-images.githubusercontent.com/8133228/53873752-477c8a80-4001-11e9-9482-6d4e9b06fbe9.png)

3. I found at least three videos don't have sound and are supposed to have, not sure if it's anyhow related, but just to write it down for later check:
-http://localhost:5304/tool/default-item-details?id=4088087@program&cid=nisv-catalogue-aggr-full-18-158
-http://localhost:5304/tool/default-item-details?id=50263@program&cid=nisv-catalogue-aggr-full-18-158
-http://0.0.0.0:5304/tool/default-item-details?id=4533072@program&cid=nisv-catalogue-aggr-full-18-158&st=%22Het%20vliegtuig%20was%20vertrokken%20vanuit%20sjarm%20al%20sjeik%20een%20plaats%20in%20egypte%20het%20was%20op%20weg%20naar%20sint%20petersburg%20in%20rusland%20maar%20kort%20na%20vertrek%20ging%20het%20helemaal%20mis%20en%20stortte%20het%20vliegtuig%20neer%20verslaggever%20david%20jan%20godfroid%20werkt%20voor%20het%20jeugdjournaal%20in%20rusland.%22

**Comment by jblom** [comment]
@lilimelgar 
- point 1 is not easy. It will have to wait until after V4 (we might be able to show the # of annotations per media object/carrier in the playlist...)
- point 2 & 3 seem to be somehow not accurate. The titles (when available) are always showing for the segments + they are all ordered chronologically (maybe you had a strange local version?) 
- point 4 is a big oops: I accidently pushed a muted player to the master (when developing it was annoying not being able to listen to music properly, because of the programs playing simultaneously ;-) )

**Comment by lilimelgar** [comment]
@jblom After testing Test version (March28), there is an issue with the playlist: http://mediasuite-test.rdlabs.beeldengeluid.nl/tool/default-item-details?id=5176026@program&cid=nisv-catalogue-aggr-full-18-158:
Items don't play
They are not in chronological order

**Comment by jblom** [comment]
@lilimelgar when I view that page, the list is in chronological order:

![Schermafbeelding 2019-03-28 om 16 39 42](https://user-images.githubusercontent.com/917310/55171183-2cbcb200-5178-11e9-9446-d7ba6bb7228b.png)

so not sure what you see?

Also as you can see the duration of each segment is hours beyond the duration of the media object. Will check if it's a problem in the metadata itself or a bug in the code

**Comment by jblom** [comment]
@lilimelgar update on this item: the metadata is lacking a startoffset, so that's why the time codes are so far off. The segments do relate to the media object, so that is correct.

Maybe @mwigham can find out why the startoffset is not there? Could you also check if you can see how many items lack the startoffset?

**Comment by mwigham** [comment]
About half the segment carriers have a startoffset. Looking at the item in question, the timecodes don't seem to be at all realistic, it seems they are just the startoncarrier converted into timecode, which gives timecodes of 8 hours and more. On this example, if I subtract the segment startoncarrier from the program startoncarrier, then I get the correct starting points. But this doesn't work with [this other example](http://mediasuite-test.rdlabs.beeldengeluid.nl/tool/default-item-details?id=5231505@program&cid=nisv-catalogue-aggr-full-18-158&st=eenvandaag). I'll look into this more tomorrow.

**Comment by jblom** [comment]
@mwigham ah that is at least a calculation to correct those. Will do that calculation (in the client side mapping) for carriers that don't have a startoffset AND are way out there.

**Comment by jblom** [comment]
@lilimelgar @mwigham 

On my local machine I've built in the said fall-back mechanism (in case of no offset, check the parent carrier). This works for the example. Will test more and then deploy it. It's all fixed in the mapping file, so I'll have to send that around too

<img width="1414" alt="Schermafbeelding 2019-03-29 om 09 59 03" src="https://user-images.githubusercontent.com/917310/55221368-98029480-5209-11e9-844f-a81322c080a3.png">

**Comment by jblom** [comment]
@mwigham the example you mentioned is strange indeed: 
- it also does not have the offset, but the same calculation does not work completely (so subtracting the program start time)
- so "not completely" in this case means means: the start times of the segments are off by exactly 6 minutes...

Now I'm trying to find where those six minutes come from...

Other than that the solution works nicely & I'll deploy that soon as well.

**Comment by mwigham** [comment]
Is it possible that that example just has bad metadata?

**Comment by jblom** [comment]
@mwigham yes that's possible. Maybe you can verify in DAAN if that record is indeed off there as well?

**Comment by lilimelgar** [comment]
@jblom: I tested in production again with the examples mentioned in this issue, and others. This is what I found:
-Issues with ordering the fragments
-Duration issues seem to be fixed
-Small usability issues (I entered them in another issue)

Here the examples from above tested again:

-http://mediasuite.clariah.nl/tool/default-item-details?id=FLM77223&cid=eye-desmet-films&st=werk. Desmet film with two carriers: OK
-http://mediasuite.clariah.nl/tool/default-item-details?id=482379@program&cid=nisv-catalogue-aggr-full-18-158&st=%22openbaar%20vervoer%22. OK
-http://mediasuite.clariah.nl/tool/default-item-details?id=50263@program&cid=nisv-catalogue-aggr-full-18-158: All OK, except that one of the program segments is not in chronological order:
![Screenshot 2019-04-10 at 15 03 57](https://user-images.githubusercontent.com/8133228/55880962-0d734b00-5ba2-11e9-90d1-33524f20dd31.png)
-This one has to be checked, since the fragment names don't correspond to the content. This item was discussed above in relation to the possibility that there is just bad metadata: http://mediasuite.clariah.nl/tool/default-item-details?id=5231505@program&cid=nisv-catalogue-aggr-full-18-158&st=eenvandaag
-http://mediasuite.clariah.nl/tool/default-item-details?id=5313446@program&cid=nisv-catalogue-aggr-full-18-158&st=aardkloot: Same issue as above, order:
![Screenshot 2019-04-10 at 15 09 40](https://user-images.githubusercontent.com/8133228/55881323-bb7ef500-5ba2-11e9-9436-4740fefe2636.png)
-http://mediasuite.clariah.nl/tool/default-item-details?id=5176026@program&cid=nisv-catalogue-aggr-full-18-158. The second item doesn't play

**Comment by mwigham** [comment]
Just looked at the Eenvandaag item in DAAN, and the segments are messed up there too - in exactly the same way as in the Media Suite. So it would seem to be a metadata error.

**Comment by jblom** [comment]
@lilimelgar @mwigham alright I am closing this one, since the remaining issue was just a data issue. If there is something wrong with the segments at a later time, please write a new issue (and this issue could be referred to if necessary)
