### ISSUE TITLE
As a user of the Media Suite, I would like to have the option to search in all layers at once

### ISSUE THREAD

**Issue by lilimelgar** [beeldengeluid/labo-components#300]
Where: Search tool, field cluster selector.

The current layers are exclusive:
-All metadata fields
--Titles
--Descriptions
--Keywords
-Enrichments
--ASR
...

This issue is about changing the search logics in these layers from the previous situation to make it inclusive:

-All (archival metadata and automatic enrichments)
-All archival metadata
--Titles
--Descriptions
--...
-Automatic enrichments
--ASR
--..

**Comment by jblom** [comment]
@lilimelgar added to the backlog. Will refine the description laterrrr

**Comment by jblom** [comment]
old issue already solved, closing
