### ISSUE TITLE
As a developer, I need to delete all annotations that have a no longer existing user project ID 

### ISSUE THREAD

**Issue by lilimelgar** [beeldengeluid/labo-components#302]
**Where**
Workspace / User projects

**Current situation**: 
If a user deletes a user project s(he) is not aware that the annotations that have the ID of that user project are not deleted (since they are stored in a different index). 

Because of this there are several "orphaned" annotations (with a project ID that no longer exists)

**Short term solution**: 
- After the release of version 3.2 we'll ask the users to delete their unused projects.
- A script that runs periodically deletes the resulting "orphaned" annotations

**Acceptance criteria**
- [ ] write a script that deletes orphaned annotations (loop through all annotations and check if the project still exists)
- [ ] do NOT delete annotations without a project ID (these are used in motu/arttube)
- [ ] test the script first on the test cluster only
- [ ] finally deploy the script on xeniaonatopp and hook it up to a cronjob. Use it to clean both test & prod (make sure it can connect to both APIs)

**Comment by jblom** [comment]
@lilimelgar thanks for creating the issue. Added the technical details & put it in the backlog

**Comment by jblom** [comment]
Issue moved to [beeldengeluid/labs-annotation-api #7](https://github.com/beeldengeluid/labs-annotation-api/issues/7) via [**ZenHub**](https://www.zenhub.com/)
