### ISSUE TITLE
As a user, I want to find user-friendly labels for the NISV collections in the Media Suite

### ISSUE THREAD

**Issue by lilimelgar** [beeldengeluid/labo-components#306]
Currently, users see complicated labels for the NISV metadata. We have seen users struggling with the list of date fields to select from. 

Current work in progress includes the creation of the labels first. The labels with be ready quite soon. They are in [this file](https://docs.google.com/spreadsheets/d/1qTExPSDEKQu-basMx-6szMsded29NzLg0CH2Im5t6JU/edit?usp=sharing)

@jblom Could you please help me writing this issue properly? the idea is to update the current labels with these ones, so they are shown everywhere in the MS. This would be a very welcome improvement for V4 hopefully!

**Comment by jblom** [comment]
@lilimelgar indeed a very important improvement. I'd say this is one for the new sprint today.  @jwassenaarbg should be able to pick this up.

**Comment by lilimelgar** [comment]
All B&G labels were updated according to the file we used for that:
Sheet ["User-friendly labels and descriptions"](https://docs.google.com/spreadsheets/d/1qTExPSDEKQu-basMx-6szMsded29NzLg0CH2Im5t6JU/edit#gid=864095883). @mwigham: Perhaps we should look at the comments and try to solve them before closing this issue? Or do we close it for now?

**Comment by mwigham** [comment]
good idea

**Comment by jblom** [comment]
@lilimelgar @mwigham ok awaiting a new spreadsheet then. In general we should think about the best way of providing "collection metadata" for all collections see this old story I created a while back for that: https://github.com/beeldengeluid/labs-search-api/issues/51

**Comment by jblom** [comment]
@mwigham @lilimelgar so the final thing is getting the latest file right?

Please let me know when it's done, so I can show you how to update it using CKAN (see https://github.com/beeldengeluid/labs-search-api/issues/53 that was just finished)

**Comment by jblom** [comment]
@lilimelgar @mwigham closing this issue, since there is nothing stopping a CKAN user (representing and institute) from updating the field descriptions. The workflow is in place.
