### ISSUE TITLE
As a developer, I need to fix a layout issue in the bookmarking (preselected) window and fix some small things related to bookmarking

### ISSUE THREAD

**Issue by lilimelgar** [beeldengeluid/labo-components#307]
Where: In the search tool, bookmarking functionality

- [x] There is a strange list of tick boxes in the window to preview selected items, on the right side (see image 1 below). When one clicks on those white "ghost" check boxes, the result gets opened, but that is already possible by clicking on the title. I guess those boxes are not meant to be there ;)
- [x] Please change text "Selected items" for "Preselected items", to make it clear that they are not bookmarked yet
- [x] Accordingly, Change text from "clear selection" to "Clear preselection"
- [x] Once the user decides to bookmark, they click on the "bookmark button". Please change the static text "Select one or more bookmark groups for your selection of resources" (Image 2) for this one: "Select one or more, or create a new bookmark group (see HowTos in the help menu)"
- [x] It should be possible to know which user project you are saving your bookmarks to, the title of the selected/active User project should appear (and be possible to change) in the bookmarking pop-up window
- [x] Bookmark button that appears in the result list bar should show a mouse over text saying "Bookmarking" (check that all other icons have mouse over texts)

**Image 1** bug
![Screen Shot 2019-03-05 at 13.24.03.png](https://images.zenhubusercontent.com/5a115fba8a75884b9087ff7a/09fa4269-3c02-4023-ba74-fe222499ca74)

**Image 2** bookmarking dialog box
![screen shot 2019-03-05 at 13 29 07](https://user-images.githubusercontent.com/8133228/53805569-c662bc00-3f4a-11e9-9023-267acd7dfd94.png)

**Comment by avlisodraude** [comment]
@lilimelgar @jblom 
Issue for labo-components project in branch:
_issue/#307-bookmarking-changes_

### What's been done?
All items in the acceptance criteria have been done. 

### Screenshots
- There is a strange list of tick boxes in the window to preview selected items, on the right side. 
![Screenshot 2019-03-26 at 15 08 06](https://user-images.githubusercontent.com/5918438/55003683-22b07d00-4fd9-11e9-8487-18c35e7234fe.png)

- Change text "Selected items" for "Preselected items", to make it clear that they are not bookmarked yet.
- Accordingly, Change text from "clear selection" to "Clear preselection"

![Screenshot 2019-03-26 at 15 09 55](https://user-images.githubusercontent.com/5918438/55003738-3c51c480-4fd9-11e9-842d-50c18aec1208.png)

- Once the user decides to bookmark, they click on the "bookmark button". Please change the static text "Select one or more bookmark groups for your selection of resources" for: "Select one or more, or create a new bookmark group (see HowTos in the help menu)"
- it should be possible to know which user project you are saving your bookmarks to, the title of the selected/active User project should appear (and be possible to change) in the bookmarking pop-up window

![Screenshot 2019-03-26 at 15 11 24](https://user-images.githubusercontent.com/5918438/55004027-beda8400-4fd9-11e9-99c2-111644a84eaf.png)

-  Bookmark button that appears in the result list bar should show a mouse over text saying "Bookmarking" (check that all other icons have mouse over texts)
![Screenshot 2019-03-26 at 15 14 18](https://user-images.githubusercontent.com/5918438/55004095-df0a4300-4fd9-11e9-8a60-eaec47400ad7.png)

**Comment by lilimelgar** [comment]
@avlisodraude: one little change in the third image: instead of "Select one or more, or create a new bookmark group (see HowTos in the help menu)", which I suggested before, please use this:
"Select one or more bookmark groups for your bookmarks, or create a new bookmark group" 
I reconsidered this, it's better not to say see "HowTos" since we would have to add that everywhere...

**Comment by avlisodraude** [comment]
@lilimelgar 
Last change to text done in the same branch

**Comment by jblom** [comment]
@avlisodraude @lilimelgar since the branch was a bit out of sync with FW's latest changes I've deleted it and put the changes directly into master. 
- I also removed the reference to the HowTos since indeed it would need to be put everywhere
- So now the title in the pop-up says: "Bookmark selection to project X"
- Above the list of bookmark groups it says: "Select one or more, or create a new bookmark group"

**Comment by lilimelgar** [comment]
@jblom and @avlisodraude, yes! everything nicely solved in production, closing it 👍
