### ISSUE TITLE
As a user I want to view the list of Field cluster in alphabetical order and add search box

### ISSUE THREAD

**Issue by avlisodraude** [beeldengeluid/labo-components#308]
As a user I want to view the list of Field cluster in alphabetical order and add search box.

**Acceptance criteria:**
The current selection list should return an ordered list of metadata fields.

**Current situation:**
![Screenshot 2019-03-11 at 14.52.03.png](https://images.zenhubusercontent.com/5a1e745d8a75884b90892ac4/af0b4002-0d15-4238-83f3-95a06a69e6f1)

A search box should be added so the user can search quickly over the long list.

**Ideal situation:**
![Screenshot 2019-03-11 at 14.54.29.png](https://images.zenhubusercontent.com/5a1e745d8a75884b90892ac4/8d077e8b-5e9d-43d3-8c0b-7dc37e8901b0)

**Comment by jblom** [comment]
@avlisodraude I left comments in the PR (trying out the code review options in GH). 

Also I found 1 bug (also in the master) + I have one remark:
- [ ] bug: if you open the dialog and close it, you cannot open it a second time
- [ ] remark: searching is nice, but each time you do, selected items are reset, so it's impossible to select items accross searches. I'd say leave this for now, but please do fix the bug + follow up on my review comments

**Comment by avlisodraude** [comment]
@jblom 
Comment regarding: bug: if you open the dialog and close it, you cannot open it a second time

Has been solved in last commit :-)

**Comment by jblom** [comment]
@lilimelgar since this story had some left over issues that are now addressed in #323 I've already merged the code for this issue (which at least I tested).

So whenever #323 is done you can test this issue as well. I'll put a reference to this issue into #323 after this.
