### ISSUE TITLE
As a user I want some enhancements to the Create Facet feature

### ISSUE THREAD

**Issue by avlisodraude** [beeldengeluid/labo-components#309]
As a user I want some enhancements to the Create Facet feature.
In the search tool we would like some changes to the New Facets feature to make it clear and more consistent for the user.

**Acceptance criteria:**

- [x] Modify link text to create a new facet from 'New +' to "Add a new facet".
- [x] Change text in the pop-up from "Create new aggregation" to "Create a new facet".
- [x] The new created facet should show on top of the default facets.

**Note:** This issue is part of #262

**Comment by avlisodraude** [comment]
@jblom @lilimelgar 

Issue for labo-components project done in branch:
 _issue/#309-enhancements-create-facet-feature_

**What's been done?**
- Modify link text to create a new facet from 'New +' to "Add a new facet".
- Change text in the pop-up from "Create new aggregation" to "Create a new facet".
- The new created facet should show on top of the default facets.

**Screencast demo**

https://drive.google.com/open?id=1rVg2WxQJfqAdRoWfxLpxrOK_tvRSgrqC

**Comment by jblom** [comment]
@avlisodraude merged this into master after quite heavy refactoring of this component's code:
- arrow functions for everything
- got rid of that toggle button (exclude facets); I hated the implementation (also triggering React warnings). Replaced that with a regular checkbox
- fixed a small bug. The top facet box could not be hidden.
- updated several CSS class names using the IDUtil (to make sure they are unique)
- Reduced 4 sorting buttons to 2 (now they alternate icon based on the sort direction)
- Now you can also see which sorting option is active (different color)

@lilimelgar should check this as well.

**Comment by lilimelgar** [comment]
@avlisodraude I tested in production and it all works OK. Only two things before closing:
- [ ] one minor thing, for you to check  if it is a bug please: When the added facet has not items, the facet goes to the bottom, not to the top (example to reproduce: Eye Films: select URL)
- [ ] Johannes and Mari? suggested that the text "Hide facet" should be "Remove facet"

**Comment by jblom** [comment]
@avlisodraude did you see the last remark? Could you check this one please?

**Comment by avlisodraude** [comment]
**@lilimelgar @jblom**
Changes suggested by @lilimelgar in her last comment from _Apr 10, 2019_ have been implemented in labo-components branch:
_issue-309-display-empty-aggr-on-top_  

Pull request has been requested to @jblom 
https://github.com/beeldengeluid/labo-components/pull/392

### Done:
- Empty Facet blocks are displayed on top of aggregation blocks.
- Rename Hide to Remove as suggested in the issue. 

### Screenshots

![Screenshot 2019-05-13 at 15.09.01.png](https://images.zenhubusercontent.com/5a1e745d8a75884b90892ac4/5f0e1111-973d-4dd7-8ba7-d04ae4e8d4e0)
![Screenshot 2019-05-13 at 15.05.08.png](https://images.zenhubusercontent.com/5a1e745d8a75884b90892ac4/b5acd3e3-4c72-48f6-8544-ccbbc8d44f5e)
![Screenshot 2019-05-13 at 15.06.08.png](https://images.zenhubusercontent.com/5a1e745d8a75884b90892ac4/d32be9c8-c92a-4eab-942e-7f57dc65757a)
