### ISSUE TITLE
As a user I want a link from the Preview (Quick view modal) to the resource itself

### ISSUE THREAD

**Issue by avlisodraude** [beeldengeluid/labo-components#313]
As a user I want a link from the Preview (Quick view modal) to the resource itself opening in a new tab in the item-details page.

Acceptance criteria:
- [x] A link button in the "Quick view" modal that opens the resource in the item-details page.

**Comment by avlisodraude** [comment]
@lilimelgar @jblom 

**Note:**
This issue is part of #262

**Issue for labo-components project done in branch:**
_issue/#313-add-link-to-item-details-in-quick-view_

**What's been done?**
In the Preview mode (Quick view) modal a new button has been added which takes the user to the corresponding resource in the item-details page.

**Screenshot of btn** 
![Screenshot 2019-03-12 at 16.28.21.png](https://images.zenhubusercontent.com/5a1e745d8a75884b90892ac4/41d875ac-2e0b-44cb-9bb4-d44c7f236747)

**@jblom:**
Since the gotoItemDetails() method was defined in the SearchHit component and the QuickViewer component does not have direct access to that method (communication between them goes through the SingleSearchRecipe via props) I moved the gotoItemDetails() method to the common parent component (SingleSearchRecipe).

**Comment by lilimelgar** [comment]
@jblom : this feature didn't go in production.

**Comment by jblom** [comment]
@lilimelgar true, I haven't looked at it yet

**Comment by jblom** [comment]
@avlisodraude @lilimelgar alright I've merged this one to master and it looks ok now (did a few minor tweaks to the code) Closing this one
