### ISSUE TITLE
As a user of the Newspaper collection I'd like more clear messages in the resource viewer

### ISSUE THREAD

**Issue by avlisodraude** [beeldengeluid/labo-components#314]
As a user of the Newspaper collection I'd like more clear messages in the resource viewer

In the Newspaper resource viewer, instead of "application?" it should say "View resource" 

![image.png](https://images.zenhubusercontent.com/5a1e745d8a75884b90892ac4/27789c99-fe1d-4720-ae7b-deeca69bb5a1)

**Acceptance criteria**
- [ ] When using the Newspaper collection and in the resource viewer instead of the current "application?" it should say "External resource".

**NOTE:** This issue is part of #262

**Comment by jblom** [comment]
@avlisodraude be careful with this one. The label on the tab is generated based on the mimeType of the "playable content"/media object. For KB the mimeType is set to application/json (which is a bit weird, but is now used to determine that the content cannot be shown inside the media suite, but instead is hosted externally)

Check the function getRenderedMediaContent() in the resource viewer. There you see the title is set based on the name of the tab, which in turn is derived from the mimeType. So for video, audio & images the tab name is fine, but for "application" it is not. 

Maybe the best solution is to add a field to the media object (in the mappings), called prettyMediaType or something

**Comment by avlisodraude** [comment]
@jblom @lilimelgar 

Issue for labo-components project done is branch:
_issue/#314-newspaper-collection-media-type_

**What's been done**
When viewing a resource for the Newspaper Collection the content tab label has been renamed from '? Application' to 'External resource'

![Screenshot 2019-03-13 at 09.34.47.png](https://images.zenhubusercontent.com/5a1e745d8a75884b90892ac4/72ef04d0-99d4-4f82-9caf-491d5e3e55ae)

**Comment by jblom** [comment]
@lilimelgar FYI: I think **external resource** fits a bit more with the other possible tab titles: video, audio, image.

We should properly address this issue when taking the resource viewer to the next level. For now this seems fine I guess

**Comment by jblom** [comment]
@avlisodraude @avlisodraude  merged this one, without testing since VPN did not work. Should be ok though, since it's such a small change

**Comment by jblom** [comment]
@lilimelgar closing this one, since it was such a tiny issue and I want to clean up a bit
