### ISSUE TITLE
As a user I want some small improvements to the Workspace

### ISSUE THREAD

**Issue by avlisodraude** [beeldengeluid/labo-components#316]
As a user I want improvements to readability in the Workspace.

**Acceptance criteria**
- [x] In workspace/projects/create: remove the checkbox (and related code) at the bottom, since it does not do anything
- [x] Instead extend the header message: "A user collection contains personal metadata and possibly links to private collection data" with an extra sentence: "Currently all user collections are private and cannot be shared with others."
- [x] remove the checkbox (and related code): "only show my projects" from the project table (see Image 4)
- [x]  In /workspace/projects. Fix the bookmark icon in the table header. It's now a weird grey square.
- [x]  There should be an option for viewing an item in a new tab (via the bookmark & annotation table; see images 2&3)

**Image 1**
![Screenshot 2019-03-13 at 11.20.09.png](https://images.zenhubusercontent.com/5a1e745d8a75884b90892ac4/4b5396f8-b5d0-485f-a7d5-090d854e9241)

**Image 2**

![Schermafbeelding 2019-03-13 om 11 55 27](https://user-images.githubusercontent.com/917310/54273904-20850200-4587-11e9-9194-f068aaced63e.png)

**Image 3**

![Schermafbeelding 2019-03-13 om 11 55 37](https://user-images.githubusercontent.com/917310/54273908-22e75c00-4587-11e9-88d4-abadbba396d8.png)

**Image 4**

![Schermafbeelding 2019-03-13 om 11 57 35](https://user-images.githubusercontent.com/917310/54273992-5629eb00-4587-11e9-9232-c585e9f9ca12.png)

**Comment by jblom** [comment]
@lilimelgar I rewrote the acceptance criteria. My view is to completely remove the private/public checkbox, since it does not do anything. Instead we simply make the user aware that by default user collections are private and cannot be shared with others.

**Comment by avlisodraude** [comment]
@jblom @lilimelgar 
Issue for labo-components done in branch 
_issue/#316-improvements-to-workspace_

**What's been done?**

__1. In workspace/projects/create: remove the checkbox (and related code) at the bottom, since it does not do anything__
![Screenshot 2019-03-14 at 14.22.36.png](https://images.zenhubusercontent.com/5a1e745d8a75884b90892ac4/6d9deb24-4065-4b7a-abff-fab0a3efcd34)
---
---
**2. Instead extend the header message: "A user collection contains personal metadata and possibly links to private collection data" with an extra sentence: "Currently all user collections are private and cannot be shared with others."**
![Screenshot 2019-03-14 at 14.25.56.png](https://images.zenhubusercontent.com/5a1e745d8a75884b90892ac4/b532286c-6d2d-480f-bbcd-afb1609628d4)
---
---
**3. Remove the checkbox (and related code): "Show only my projects" from the project table. AND**
**4. In /workspace/projects. Fix the bookmark icon in the table header. It's now a weird grey square.**
![Screenshot 2019-03-14 at 14.30.19.png](https://images.zenhubusercontent.com/5a1e745d8a75884b90892ac4/f86d8e14-7f85-48ba-ba65-caebc2643bc9) 
---
---
**5. There should be an option for viewing an item in a new tab (via the bookmark & annotation table; see images**
![Screenshot 2019-03-14 at 14.31.03.png](https://images.zenhubusercontent.com/5a1e745d8a75884b90892ac4/64afc4e6-0d79-4c49-9d2d-9af06e53504c) 
**NOTE:** Regarding this options I added a new button to open the resource directly in the item-details page. Now the 'View' button enable the new functionality (opening the resource in the item-details page) and the 'Preview' button is the previous 'View' button (only the name was changed since it makes more sense that this is a preview mode). The code and relevant functions have been renamed to make clear these changes.

**Comment by jblom** [comment]
@avlisodraude you forgot to remove 2 more references to the isPrivate parameter (for project):

Project table:

![Schermafbeelding 2019-03-27 om 07 15 32](https://user-images.githubusercontent.com/917310/55054574-a8c3d680-5060-11e9-852a-1c4dc9ac8efb.png)

Project details page:

![Schermafbeelding 2019-03-27 om 07 14 49](https://user-images.githubusercontent.com/917310/55054579-ae212100-5060-11e9-8d27-5c43910c9491.png)


I removed those now. Continuing review

**Comment by jblom** [comment]
@avlisodraude @lilimelgar 

Replaced the PREVIEW text with the same icon used in the search results (for quickview). In general I don't really like the two buttons, so will ask FW later if there is a nicer solution

![Schermafbeelding 2019-03-27 om 08 19 35](https://user-images.githubusercontent.com/917310/55057311-1ffd6880-5069-11e9-8764-b666064b80a4.png)

Also removed the "Add collaborator" + "Collaborators" stuff from the project details view:

![Schermafbeelding 2019-03-27 om 08 19 51](https://user-images.githubusercontent.com/917310/55057314-21c72c00-5069-11e9-85d8-73f4bb7d5ef4.png)

Will merge now, since we have to  move on. Please test though

**Comment by lilimelgar** [comment]
@jblom: I tested this in production, it works well, the icons have very clear text on mouse-over, it's fine for now ;). Also the "add collaborator" text is gone.
