### ISSUE TITLE
As a user I want some improvements to the Single Search tool

### ISSUE THREAD

**Issue by avlisodraude** [beeldengeluid/labo-components#317]
As a user I want some improvements to the Single Search tool.

When users save a query using the "Save query" button,  the user should be able  to: 

**Acceptance criteria**
- [x] See the parameters for the saved query. Make them clearly visible so it's clear for the user what query is being saved 
- [x] In the list of previous queries add a header that says: "Saved queries in this User project".
- [x] It also shows to which User project the user is saving the query -this is new to be done, not there.
- [x] In the save query modal: Once a query is saved, the user should get a confirmation message that the query has been saved in the Workspace (name of user project).
- [ ] In the Search tool, change the text in the search box here below, Instead of "search" write: Search (see "how-tos" in the help "?" button).
- [x] put the table with already saved queries in a "flexbox", collaps it by default

**Comment by avlisodraude** [comment]
@lilimelgar @jblom 

Issue for labo-components project done in branch:
_issue/#317-single-search-enhancements_

**What been done?**
All options for the 'Acceptance criteria' plus :

- field validation. ie, if the user tries to save a query without assigning it a name an error message will be displayed. No query will be saved until a name has been assigned.
- The alert message for when saving bookmarks has also been replace by a modal.

**Screencast**

https://drive.google.com/open?id=1SsQu9x_z_bcBZ5p5F_RYGZDFbP3c7Tue

**Note**
Issue part of #262

**Comment by jblom** [comment]
@avlisodraude @lilimelgar alright after doing quite some restyling & code cleaning I've merged this issue with master, so Werner can also merge this in time, avoiding conflicts later on.

So what remains is testing from @lilimelgar. From my side I'd say it's fine and indeed a nice improvement

**Comment by lilimelgar** [comment]
@jblom @avlisodraude Tested in production, everything OK, nice improvements! the only non implemented thing was the change in the text to show in the query box, but this was fixed in another way by Werner, so, closing this one :)
