### ISSUE TITLE
As a user I want some improvements to the  Create a new cluster modal

### ISSUE THREAD

**Issue by avlisodraude** [beeldengeluid/labo-components#323]
**Acceptance criteria**:
- the issues in #308 are all done
- change the HTML multi select element with a "two boxed approach", where the user can select one or more fields from the left box and put them into the right box (representing: selected items)
- users can remove items from the right box, so they are put back in the left box again
- user can search through both boxes in separate search boxes (or something better than this, please research a nice solution)

**Comment by avlisodraude** [comment]
**@lilimelgar @jblom** 
Issue for labo-components project done in branch: 
_issue/#323-improvements-to-create-new-cluster-modal_
---
#### What's been done?
- The user is able to select items in a 2 column interface.
- Validation is added to the component (the user must add a name to the new cluster and selected at least 1 field)
---
#### Screenshot
![Screenshot 2019-03-25 at 08.20.06.png](https://images.zenhubusercontent.com/5a1e745d8a75884b90892ac4/c9a098fe-e1f2-4aea-86c6-0bcccde6e149)
---
#### Screencast
https://drive.google.com/open?id=1vbEjFOlsybpcI8xrVp9LX6mQXTqTR06X

**Comment by avlisodraude** [comment]
@jblom 
The original pull request has been closed and a new pull request has been created with an up to date Master version. 
### Branch name:
_issue/#323-improvements-to-create-new-cluster-modal-v2_

### Pull request:
https://github.com/beeldengeluid/labo-components/pull/341

**Comment by jblom** [comment]
@lilimelgar @avlisodraude ok I tested & merged this (after refactoring mainly CSS & mark-up). Works nicely! 

Please test

**Comment by lilimelgar** [comment]
Tested in production, nice feature! works well. I also tested that the field clusters are stored in the query, also works well!
