### ISSUE TITLE
bug: the first search after a "CLEAR/RESET SEARCH" matches all & disregards the search term

### ISSUE THREAD

**Issue by jblom** [beeldengeluid/labo-components#333]
how to reproduce.
- run a query
- click RESET QUERY (on the right)
- enter a really nonsense query, e.g. laisdfasdfhASFASDA
- the search returns ALL results from the collection

**Comment by jblom** [comment]
@lilimelgar @avlisodraude fixed this one in the master. You need the latest mappings on Slack for this to work. Please test

**Comment by lilimelgar** [comment]
@jblom I tested this one on Production and the bug is fixed.
