### ISSUE TITLE
As a user I want to keep my selected facets when  a search is done without a search term

### ISSUE THREAD

**Issue by avlisodraude** [beeldengeluid/labo-components#344]
As a user I want to keep my selected facets when  a search is done without a search term.

**Comment by avlisodraude** [comment]
### Issue :

When a user queries a collection without adding a search term and filters by any other criteria (Facets, Metadata, etc) and then he/she select an item to view in the item details page, when the user decides to go back to the search results via the  "Back to results" button the whole search is removed.

### Cause:
In the QueryBuider a check for 'searchTerm' is done and if no query term is provided doSearch function is not run, which mean that the user comes back to the Single Search Query with an empty result set.

**Comment by avlisodraude** [comment]
@jblom 
Issue done in labo-component branch:
_issue/#344-remove-searchTerm-restriction-4-queries_

### What's been done?
query term check has been removed.

Issue tested with B&G and KB collection with no noticeable effects in terms of performance.

**Comment by lilimelgar** [comment]
@avlisodraude What a nice issue! I always thought this was not possible. Tested in production, works well :)
