### ISSUE TITLE
As a developer, I need to update the links to the new documentation pages

### ISSUE THREAD

**Issue by lilimelgar** [beeldengeluid/labo-components#346]
The Documentation pages have changed structure. This has made the previous links outdated.

ToDos:
- [x] Change the links to the Question mark icons that appear in different pages on the top right (see list 1)
- [x] Change the order of links, and add one link in the Main menu: Learn (see list 2)
- [ ] Fix issue in the Documentation pages: the menu does not collapse properly (check the behavior of the table of contents on the left, that all levels collapse and expand properly, for example, the menu doesn't collapse with third level items (e.g., http://mediasuite.clariah.nl/documentation/howtos/user-projects/create)

**LIST 1: Links to update for Question mark buttons to work again**
PAGE ->>> OLD LINK TO DOCUMENTATION ->>> NEW LINK TO DOCUMENTATION (UPDATE IN QUESTION MARK ICON)

- http://mediasuite.clariah.nl/data ->>> http://mediasuite.clariah.nl/documentation/data ->>> http://mediasuite.clariah.nl/documentation/howtos/data

- http://mediasuite.clariah.nl/tools  ->>> http://mediasuite.clariah.nl/documentation/tools ->>> http://mediasuite.clariah.nl/documentation/howtos/tools

- http://mediasuite.clariah.nl/tool/collection-inspector  ->>> http://mediasuite.clariah.nl/documentation/tools/collection-inspector ->>> http://mediasuite.clariah.nl/documentation/howtos/collection-inspector

- http://mediasuite.clariah.nl/tool/exploratory-search  ->>> http://mediasuite.clariah.nl/documentation/tools/exploratory-search ->>> http://mediasuite.clariah.nl/documentation/howtos/exploratory-search

- http://mediasuite.clariah.nl/tool/single-search  ->>> http://mediasuite.clariah.nl/documentation/tools/single-search ->>> http://mediasuite.clariah.nl/documentation/howtos/single-search

- http://mediasuite.clariah.nl/tool/query-comparison  ->>> http://mediasuite.clariah.nl/documentation/tools/query-comparison ->>> http://mediasuite.clariah.nl/documentation/howtos/query-comparison

- http://mediasuite.clariah.nl/workspace/projects ->>> http://mediasuite.clariah.nl/documentation/workspace/user projects ->>> http://mediasuite.clariah.nl/documentation/howtos/user-projects

- http://mediasuite.clariah.nl/workspace/projects/create ->>> http://mediasuite.clariah.nl/documentation/workspace/user-projects/create ->>> http://mediasuite.clariah.nl/documentation/howtos/user-projects/create

- http://mediasuite.clariah.nl/workspace/projects/[project ID]/edit ->>> http://mediasuite.clariah.nl/documentation/workspace/user-projects/edit ->>> http://mediasuite.clariah.nl/documentation/howtos/user-projects/edit

- http://mediasuite.clariah.nl/workspace/projects/[project ID]/details ->>> http://mediasuite.clariah.nl/documentation/workspace/user-projects/details ->>> http://mediasuite.clariah.nl/documentation/howtos/user-projects/details

- http://mediasuite.clariah.nl/workspace/projects/[project ID]/bookmarks ->>> http://mediasuite.clariah.nl/documentation/workspace/user-projects/bookmarks ->>> http://mediasuite.clariah.nl/documentation/howtos/user-projects/bookmarks

- http://mediasuite.clariah.nl/workspace/projects/[project ID]/annotations ->>> http://mediasuite.clariah.nl/documentation/workspace/user-projects/annotations ->>> http://mediasuite.clariah.nl/documentation/howtos/user-projects/annotations

- http://mediasuite.clariah.nl/workspace/projects/[project ID]/queries ->>> http://mediasuite.clariah.nl/documentation/workspace/user-projects/queries ->>> http://mediasuite.clariah.nl/documentation/howtos/user-projects/queries

- http://mediasuite.clariah.nl/workspace/projects/[project ID]/tool-sessions ->>> http://mediasuite.clariah.nl/documentation/workspace/user-projects/tool-sessions ->>> http://mediasuite.clariah.nl/documentation/howtos/user-projects/tool-sessions

- http://mediasuite.clariah.nl/workspace/collections/create ->>> http://mediasuite.clariah.nl/documentation/workspace/user-collections/create ->>> http://mediasuite.clariah.nl/documentation/howtos/user-collections/create

- http://mediasuite.clariah.nl/workspace/collections/[user collection ID]/edit ->>> http://mediasuite.clariah.nl/documentation/workspace/user-collections/edit ->>> http://mediasuite.clariah.nl/documentation/howtos/user-collections/edit

**LIST 2: Links to update in the Main menu -> Learn **
- FAQ: OK
- Quick start guide: OK
- Research projects: delete from this menu
- HowTos: add item to menu, link: http://mediasuite.clariah.nl/documentation/howtos
- Troubleshooting: OK
- Forum: OK, change label to: Help & feedback forum
- Blog: OK, change label to: Blog and News
- All Documentation: OK
- All screencasts: Delete from this menu

**Comment by avlisodraude** [comment]
### @lilimelgar  @jblom 
Issue done in both projects (clariah-mediasuite and labo-components)
branches for testing:

**Project labo-components**
_issues/#346-update-links-labo_

**Project clariah-mediasuite**
_issues/#346-mediasuite_

To tes update both project with the already mentioned branches.

All acceptance criteria has been done with the exception of point (not clear explanation):
> Fix issue in the Documentation pages: the menu does not collapse properly (check the behavior of the table of contents on the left, that all levels collapse and expand properly, for example, the menu doesn't collapse with third level items (e.g., http://mediasuite.clariah.nl/documentation/howtos/user-projects/create)

@lilimelgar : Please check carefully every link. There are still help pages with no content and the message as the following screenshots show:
<img width="505" alt="Screenshot 2019-03-28 at 20 17 56" src="https://user-images.githubusercontent.com/5918438/55187765-24756e80-519a-11e9-903f-c25766291a35.png">

Regarding list 2. All done but the list does not correspond accurately with the current menu (compare list 2 with the next screenshot)
 
<img width="275" alt="Screenshot 2019-03-28 at 20 25 34" src="https://user-images.githubusercontent.com/5918438/55187867-4f5fc280-519a-11e9-8a9b-711c8ff3fca9.png">

@lilimelgar : Please check this point also. Once everything is ok let @jblom know so he can merge both branches. If there any changes let me know in the comments to make the corresponding changes.

**Comment by jblom** [comment]
@avlisodraude @lilimelgar I merged the two and I guess it looks good.

About the menu. It now looks like list 2, except that Troubleshooting is missing. Do I need to add this one?
![Schermafbeelding 2019-04-01 om 09 41 31](https://user-images.githubusercontent.com/917310/55311185-8ec03480-5462-11e9-8177-fdc248a59693.png)

**Comment by lilimelgar** [comment]
Tested in production, all links work OK!
