### ISSUE TITLE
As a user I want the menu in the documentation pages to work properly

### ISSUE THREAD

**Issue by avlisodraude** [beeldengeluid/labo-components#347]
### As a user I want the menu in the documentation pages to work properly

This issue has been taken as a separated issue from #346 

Fix issue in the Documentation pages: the menu does not collapse properly (check the behavior of the table of contents on the left, that all levels collapse and expand properly, for example, the menu doesn't collapse with third level items (e.g., http://mediasuite.clariah.nl/documentation/howtos/user-projects/create)

### Issue description
The documentation menu has (atm) a 3 level menu and every time a parent menu is opened all its children (2nd/3rd level) elements are visible by default (see screenshot)

<img width="273" alt="Screenshot 2019-03-31 at 15 34 16" src="https://user-images.githubusercontent.com/5918438/55289746-d4312300-53ca-11e9-888d-9f388d967e36.png">

### Desired behaviour
Whenever a 2nd/3rd level menu item is selected (active) only its children elements should be visible.

**Comment by avlisodraude** [comment]
@lilimelgar  @jblom 
Issue done for clariah-mediasuite project on branch:
_issue/347-fix-issue-in-doc-menu_

### What's been done?
Now whenever a 2nd or 3rd level menu item is selected only its children menu options is visible and not all other menu options non related to the parent menu. See screenshot:

... coming when vpn comes back...

**Comment by jblom** [comment]
@avlisodraude @lilimelgar merged this. Seems to work fine (haven't checked in super detail).

One thing I'd add at some point is: when you've selected e.g. "See details" (see screenshot 2) I'd expect the "Work with the Workspace's user projects" also to be highlighted in some way. Now the highlighting fully goes to "See details".

**Comment by lilimelgar** [comment]
Tested in production, it works as expected. @jblom: I didn't see the issue you describe above, I suppose it was fixed, so, closing this one.
