### ISSUE TITLE
As a user I want an issue with the layout fixed

### ISSUE THREAD

**Issue by avlisodraude** [beeldengeluid/labo-components#355]
Issue:

In the Single Search recipe, in the block shared between Facets and the Result list in some Width ranges they overlap each other (See screenshot)
![Screenshot 2019-04-01 at 18.04.26.png](https://images.zenhubusercontent.com/5a1e745d8a75884b90892ac4/5cd61414-df13-4ff9-afe4-1c1a5f29618d)

**Comment by avlisodraude** [comment]
@jblom 
Issue for labo-components project done in branch:
_issue/#355-fix-issue-insingleSeach-layout_

### What's been done?
Media query width modified. Now using the same width as in the description a reference the issue is gone (see screenshot)

### Pull Request created
https://github.com/beeldengeluid/labo-components/pull/356
![Screenshot 2019-04-01 at 18.06.22.png](https://images.zenhubusercontent.com/5a1e745d8a75884b90892ac4/46da823c-8101-4453-bb34-b639fa8be9e9)

**Comment by jblom** [comment]
@avlisodraude I've also directly merged this one. Will check it out later

**Comment by lilimelgar** [comment]
@jblom I tested this one in production and works as expected.
