### ISSUE TITLE
As a user I want the comparison tool to work when no data or dateRange is present

### ISSUE THREAD

**Issue by avlisodraude** [beeldengeluid/labo-components#357]
### Issue:

In the comparison tool when comparing queries without a dateRange being selected and/or when the query returns no data the application breaks (see screenshots)

![Screenshot 2019-04-02 at 01.37.27.png](https://images.zenhubusercontent.com/5a1e745d8a75884b90892ac4/85c4702a-659a-4223-8a71-939cf9001502)
![Screenshot 2019-04-02 at 01.37.01.png](https://images.zenhubusercontent.com/5a1e745d8a75884b90892ac4/20443310-5eb5-4bec-814b-ab76868cea52)

### To reproduce the issue:
1. In the comparative tool select the 'Bookmark-test' project and run the following query which has no dateRange selected:
![Screenshot 2019-04-02 at 01.40.01.png](https://images.zenhubusercontent.com/5a1e745d8a75884b90892ac4/3be4c4f0-f0f7-43c0-9288-34c1fad60282)
2. In the same project select the following query which returns no data:
![Screenshot 2019-04-02 at 01.41.33.png](https://images.zenhubusercontent.com/5a1e745d8a75884b90892ac4/daa5bf98-356c-4941-acf5-e2725549d461)

**Comment by avlisodraude** [comment]
@jblom 
Working issue in labo-components branch:
_issue/#357-bug-in-comparison-tool-for-no-dateRange-and-no-data_

### Done so far:
async queries modified (to clean a bit the mess) and a checking is done before querying to avoid sending queries without dateRange selected.

Regarding the no data returned by the query. It seems that moving the queryCollectionDetails block outside the checking for data solves the issue since the queries don't break the app and the collection details is displayed correctly.

### To do still:
Some sort of error reporting to let the user know why there is no graph for the selected query/ies.

**Comment by jblom** [comment]
@avlisodraude ok thanks. I've directly merged and will now check some more.

**Comment by lilimelgar** [comment]
I tested the comparative when doing the screencast, and now a bit more in production, it all works correctly and smoothly, but I did not do structured tests with old queries or different types of queries, only simple testing. The styling has also improved. @jblom Please let me know if you want me to test more properly before closing.

**Comment by jblom** [comment]
@lilimelgar this is enough for now. Getting rid & testing old data should be addressed separately. Closing this
