### ISSUE TITLE
As a user I want improvements to Query Info blocks

### ISSUE THREAD

**Issue by avlisodraude** [beeldengeluid/labo-components#362]
## As a user I want improvements to the "Query Info blocks" in the Comparison recipe.

**In some cases the query info blocks don't display properly** 

### Issues:
- **In some situations the "Query info block" stretches the whole width of the available space (see screenshot)**

![Screenshot 2019-04-03 at 13.58.24.png](https://images.zenhubusercontent.com/5a1e745d8a75884b90892ac4/caa16e99-c111-4b1f-bf85-b9478d0b0fef) 
--- 
- **The space (padding) between the header and the content is to small which doesn't make the title distinguable from the query content (see screenshot)**

![Screenshot 2019-04-03 at 13.58.41.png](https://images.zenhubusercontent.com/5a1e745d8a75884b90892ac4/5b02011b-6410-45f6-a4bd-e508f900c78f)

---

- **In long queries scrolling is enabled due to a fixed height** 

![2019-04-03_14-12-56 (1).gif](https://images.zenhubusercontent.com/5a1e745d8a75884b90892ac4/ac5bf0c4-e1bb-4fde-824b-bfb145b0fb34)

---

- **Because of the fixed height some containers when used more space than needed (see screenshot)**

![Screenshot 2019-04-03 at 15.10.25.png](https://images.zenhubusercontent.com/5a1e745d8a75884b90892ac4/f8b7df18-3ea4-4816-8409-549e6b64a1bb)

---

- **When the error message is shorter than its siblings the shorter message does not stick to the bottom of the container (see screenshot)**

![Screenshot 2019-04-03 at 13.59.38.png](https://images.zenhubusercontent.com/5a1e745d8a75884b90892ac4/b8aa1309-ca7d-49bf-903d-bb33e90211a3)

**Comment by avlisodraude** [comment]
**@jblom @lilimelgar**
**Issue done for labo-components in branch:**
_issue/#362-query-info-blocks-improvements_

### What's been done
All changes involved pure CSS. 2 files involved:
_variables.scss: 1 media query variable added to deal with break points.
QueryInfoBlock.scss: All Styling changes have been done in the corresponding file.

#### Based on the description:
- Blocks have equal width regardless the available space in their current row (see screenshot)

![Screenshot 2019-04-03 at 15.15.09.png](https://images.zenhubusercontent.com/5a1e745d8a75884b90892ac4/f888536b-5f9d-4bde-8da8-c1ceb15dccb8)

--- 

- Extra space (padding) has been added between the header and its content

![Screenshot 2019-04-03 at 15.29.55.png](https://images.zenhubusercontent.com/5a1e745d8a75884b90892ac4/fd7e62ea-dddd-4792-8d0e-dc7b1162b0e1)

---

- Fixed width has been removed and content is now "flexible" (adapt) to the available height space of the longest block in the current row (see screenshot)

![Screenshot 2019-04-03 at 15.14.54.png](https://images.zenhubusercontent.com/5a1e745d8a75884b90892ac4/66b3697d-50a7-4e0c-9cc4-531e44f19329) 

---

- Fixed issue with error messages not sticking to the bottom of the block container (see screenshot)

![Screenshot 2019-04-03 at 15.14.54.png](https://images.zenhubusercontent.com/5a1e745d8a75884b90892ac4/f9a715ae-a762-4b20-ac47-a2d947fd5d97)
---

**Comment by jblom** [comment]
@avlisodraude nice work, the css was indeed a bit clunky, merged it right away!
