### ISSUE TITLE
As a user I want  to be able to search within the Facets/Aggregation lists

### ISSUE THREAD

**Issue by avlisodraude** [beeldengeluid/labo-components#368]
### Motivation
Some aggregation lists display long lists of elements, ie, in 'Keyword' in B&G Collection we have 1751 options to select from. This makes selection process quite long.

### Acceptance criteria
As a user I want a search box that allow me to filter items from long lists so it will be easy to filter my search.

![Screenshot 2019-04-08 at 09.10.13.png](https://images.zenhubusercontent.com/5a1e745d8a75884b90892ac4/bc58fc6f-9288-42ce-8be6-4a80ae822c59)

**Comment by avlisodraude** [comment]
**@jblom @lilimelgar** 
**issue for labo-components project done in branch:**
_issue/#368-add-search-to-facets-groups_

### What's been done?
- A search box has been added per each facet's block which allows to filter the list of items.
- Every selected item shows on top of the list.
- When there are less items than the minimal amount to show the "Show More" link/btn is not displayed.
 
### Screencast:
https://drive.google.com/open?id=1GpW02cmiQTxmcgM2l00Q8H2XMBvHlSyj

**Comment by avlisodraude** [comment]
**@jblom**
 
There is already a pull request for this issue at:
https://github.com/beeldengeluid/labo-components/pull/371

**Comment by avlisodraude** [comment]
**@jblom**

All comments to the pull request have been addressed and both components (AggregationList / AggregationBox) have been cleaned up and duplicated functions have been removed. 

Now all functionality for each block is handled by the AggregationBox component (with the exception of onClick events which pass responsibility to its parent)

**Comment by jblom** [comment]
@avlisodraude the functionality looks & works nicely I think. I did made quite some changes to the CSS part though.

Closing this for now. @lilimelgar can test in hindsight (added "help wanted" label)

**Comment by lilimelgar** [comment]
Tested in test version with different collections, all OK

**Comment by jblom** [comment]
@lilimelgar check!
