### ISSUE TITLE
As a developer, I need to fix a broken link to the Resource viewer help content

### ISSUE THREAD

**Issue by lilimelgar** [beeldengeluid/labo-components#373]
In the Resource viewer, the link to the question mark help menu is broken:

![Screenshot 2019-05-01 at 12.22.21.png](https://images.zenhubusercontent.com/5a115fba8a75884b9087ff7a/4759d6a3-4f4b-4830-b34b-8ece21d026ab)

@jblom, we please need it corrected in production before May 9 (for a course with students). Thanks

**Comment by jblom** [comment]
@lilimelgar ok assigned it to @avlisodraude. Could you provide the correct link?

**Comment by avlisodraude** [comment]
**@jblom**
 
**Issue done in labo-components branch:**
_issue/#373-broken-help-link_

### Pull request 
_https://github.com/beeldengeluid/labo-components/pull/391_

### Screenshot
![Screenshot 2019-05-13 at 13.52.36.png](https://images.zenhubusercontent.com/5a1e745d8a75884b90892ac4/6ae614ff-9d4f-41a0-a80b-73729e7e039f)

**Comment by jblom** [comment]
@avlisodraude @lilimelgar done
