### ISSUE TITLE
As a developer, I need to add a "loading results" message to the graphics

### ISSUE THREAD

**Issue by lilimelgar** [beeldengeluid/labo-components#381]
-Where:
Search tool, timeline chart
Inspector tool, timeline chart

-Problem:
Sometimes the graphics take long to load the data, creating confusion when the values don't change immediately. Example: Search tool, KB collection, switching from absolute to relative view for the whole collection takes a long time (the first time), and there is no indication that the application is working on it. See [screencast](https://drive.google.com/drive/u/1/folders/0B8StOK8IHMiQX0F1akJhLUV2akE).

**Comment by jblom** [comment]
@lilimelgar @avlisodraude cannot reproduce this one, so closing it for now
