### ISSUE TITLE
As a developer, I could try to suggest adjustments to the original Open Beelden Eye data to make their dates better

### ISSUE THREAD

**Issue by lilimelgar** [beeldengeluid/labo-components#382]
In the Open images (Eye) there are some items from 2010, but that is the wrong date.

Johannes says: 
"They certainly don't look right indeed. However, when opening the items in the source catalog, the same date appears. Seems therefore wrong at the source and not with us. Might give them a list with these items so they can generate a new dump."

Examples:
Correct one: https://www.openbeelden.nl/media/32822
Wrong ones:
https://www.openbeelden.nl/media/104783
https://www.openbeelden.nl/media/104976

Steps:
-First contact Eye to ask them to correct their data
-When done, create a new dump to the MS

**Comment by jblom** [comment]
Issue moved to [beeldengeluid/labs-importer #28](https://github.com/beeldengeluid/labs-importer/issues/28) via [**ZenHub**](https://www.zenhub.com/)
