### ISSUE TITLE
As a developer, I need to check accuracy of information in the tool tip for dates

### ISSUE THREAD

**Issue by lilimelgar** [beeldengeluid/labo-components#386]
There is a tooltip that currently shows in the date filters:

![Screenshot 2019-05-02 at 14.41.00.png](https://images.zenhubusercontent.com/5a115fba8a75884b9087ff7a/e586ef2c-5988-4a06-aea9-c90bce315ffd)

@jblom Does this information apply to all collections? If so, please let me know to add to the documentation, otherwise, shall we rephrase the tooltip?

**Comment by jblom** [comment]
@lilimelgar yes this applies to all collections
