### ISSUE TITLE
As a user, I want the information on number of items in the collection to be displayed correctly

### ISSUE THREAD

**Issue by mwigham** [beeldengeluid/labo-components#406]
In the Search tool, for the nisv-catalogue-radio collection in the test environment, the number of items in the collection is shown to be -1. The number of results in the list is correct (405.526).

![image](https://user-images.githubusercontent.com/38520885/58858324-9345db00-86a7-11e9-9416-dbe41fe31419.png)

**Comment by jblom** [comment]
@mwigham will check this one out. Has something to do with my latest changes

**Comment by jblom** [comment]
@mwigham ok solved this one, this was a really stupid edge case, because of a sloppy way of error checking (my bad) if the collection metadata retrieved from the server is ok.

Closing this one instantly. This will be deployed on test soon.
